### ISSUE TITLE
Some notes from initial use

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba#151]
I just started playing with this and I like it.  There are a few things I'd change in the scaffolding/conf.

1. dbtemplate in conf and set to template1 (or else create a template as variable). I notice Odoo has recently switched back to template0 default, but for me, if you want to populate extensions cleanly, template1 is better as long as you set locale.

2. Installing unaccent (or any other extension) - install on template1 (or above template var). The problem is otherwise first run the db doesn't exist.  I actually install on both template1 and attempt on the db, just in case.

3. db init args in common.yaml db-> environment IMHO POSTGRES_INITDB_ARGS: "--data-checksums --locale=C --encoding=UTF8" should be set as a minimum default. --data-checksums are critical for production and the performance hit is less than 1% for other environs.  Again the locale setting is critical, otherwise btree indexes useless for like and ilike searches.

**Comment by gdgellatly** [comment]
Will do.

**Comment by Yajo** [comment]
Closing due to repo split explained in #157. Feel free to reopen in https://github.com/Tecnativa/doodba-scaffolding if this is still an issue. Thanks!
