### ISSUE TITLE
Help please! Quick guide Scaffolding don´t work in my Debian Stretch Virtual Machine

### ISSUE THREAD

**Issue by karistio** [Tecnativa/doodba#173]
I cloned the repo, branch scaffolding, as in the "quick guide":

```
root@dockvm:~#  git clone https://github.com/Tecnativa/doodba-scaffolding.git kaia
cd kaia
root@dockvm:~/kaia# ln -s devel.yaml docker-compose.yml
root@dockvm:~/kaia# chown -R $USER:1000 odoo/auto
root@dockvm:~/kaia# chmod -R ug+rwX odoo/auto
root@dockvm:~/kaia# export UID GID="$(id -g $USER)" UMASK="$(umask)"
root@dockvm:~/kaia# docker-compose build --pull
-bash: docker-compose: command not found
```

I have followed all the steps of the quick guide that have been working well but when I get to the instruction 'docker-compose build --pull' the answer is that the docker-compose command has not been found.

I am a beginner in these topics so I would appreciate it if anyone could help me move forward with the installation of Doodba. My goal is to update from Odoo8 to Odoo11 and I have read that Pedro Baeza advised doing it with Doodba.

**Comment by karistio** [comment]
I apologize for the lines that are crossed out which has happened against my will. They should not have any stingray.

**Comment by Yajo** [comment]
Hi there!

Doodba is using a set of tools behind the scenes, and you are supposed to be already familiar with them when using doodba.

One of such tools is `docker-compose`. The error message means it is not installed, so obviously you must install it.

Its docs can be found in https://docs.docker.com/compose/overview/, please refer there for more details.

Regards.

**Comment by karistio** [comment]
Hi Yajo!
I am very grateful for your answer because it has made clear to me that prior to the installation of doodba I must have installed docker-compose.

But I have a question. I do not know if I should install docker-compose inside the docker 'my project' (which is quoted in the quick-guide of Scaffolding) that in my case is called 'kaia' or on the contrary I have to install it directly in the Debian virtual machine .

Thank you very much for your attention. Greetings.

**Comment by Yajo** [comment]
> I have to install it directly in the Debian virtual machine

Yes, there.

**Comment by karistio** [comment]
Thank you very much, Yajo.

I followed your instructions and installed docker-compose directly on the Debian Virtual Machine.

Then I tried again to install my Doodba project and I miss a warning saying that I can not connect with Docker daemon and that I need to install Docker.

I thought that Doodba is a docker in himself but basic. If it turns out that you need a previous installation of Docker I dare to suggest that it would be convenient to add in the Readme file that, as prerequisites, Dockker-compose and Docker must first be installed.

Thank you very much for your attention. Thank you very much, Yajo.

I followed your instructions and installed docker-compose directly on the Debian Virtual Machine.

Then I tried again to install my Doodba project and I miss a warning saying that I can not connect with Docker daemon and that I need to install Docker.

I thought that Doodba is a docker in himself but basic. If it turns out that you need a previous installation of Docker I dare to suggest that it would be convenient to add in the Readme file that, as prerequisites, Dockker-compose and Docker must first be installed.

Thank you very much for your attention.Thank you very much, Yajo.

I followed your instructions and installed docker-compose directly on the Debian Virtual Machine.

Then I tried again to install my Doodba project and I miss a warning saying that I can not connect with Docker daemon and that I need to install Docker.

I thought that Doodba is a docker in himself but basic. If it turns out that you need a previous installation of Docker I dare to suggest that it would be convenient to add in the Readme file that, as prerequisites, Dockker-compose and Docker must first be installed.

Thank you very much for your attention. Greetings.
