### ISSUE TITLE
Suggested Development Workflow

### ISSUE THREAD

**Issue by livingmine** [Tecnativa/doodba#180]
This is more of a question than an issue. When doing a development in local machine using docker, one can use volumes to attach source codes in local file to the running container. Combine that with the ```--dev reload``` options, theoretically we can achieve auto reload which saves the development time. 

However, things aren't working the way i expected. From the screenshot below, we can see that the AutoReload watcher is running and watching few files inside the container, which of course i should not modify them to test the AutoReload.
![image](https://user-images.githubusercontent.com/7286614/48543962-321a0e00-e8f5-11e8-93a2-e2c6caf25a3b.png)
Instead, i should be editing the corresponding mapped local file, which if i inspect from the doodba's source code is located [here](https://github.com/Tecnativa/doodba-scaffolding/blob/2b08cb3f123986e5161b77f5b7c6e1100f96318f/devel.yaml#L39). However, editing those files does not trigger the AutoReload. Am i missing something? If my thought process is incorrect then what is the best practices on doing local development when using doodba as the development environment?

**Comment by Yajo** [comment]
I have never been able to use the autoreload. One issue you might run into is the maximum files allowed to be watched in your host system. I don't remember quite well what's the way to configure that, but just google for it.

I think we should also include an additional dependency called watchdog, which isn't shipped currently with doodba. Try adding it to your `dependencies/pip.txt` file and rebuild.

If you get to make it work smoothly, then we could add the missing pieces and docs.

**Comment by livingmine** [comment]
So how should we develop a custom module using a doodba as the development environment? Should we stop the container and rebuild it every time we want to see changes? Mind to share your experiences with this?

**Comment by livingmine** [comment]
@Yajo Thanks for sharing your rule of thumb!

As a comparison, i've tried the odoo's official docker image and the AutoReload functionality is working . One thing that i notice is that they use python3-watchdog debian's package instead of watchdog pip's package. Other than that i'm still looking for a way to get it working.

**Comment by pedrobaeza** [comment]
If it's a light dependency, then OK, but disabling the feature by default.

**Comment by livingmine** [comment]
@pedrobaeza Yes i have, but i agree with @Yajo that if the devs know what they're doing they'll realize that they need to do the full restart anyway. I think we're all talking about two problems in this issue:
1. The fact that watchdog is not shipped in this image.
2. Even though it is shipped, still it does not work just like in odoo's official docker image.

**Comment by pedrobaeza** [comment]
We weren't aware about second point. @Yajo, maybe this is because all the links stuff...

**Comment by HaGuesto** [comment]
@Yajo I'm trying out the doodba scaffolding and I have to say I realy like your project. 

However, I do not manage to get the autoreload going even though watchdog is included. Is there any update or doc how to do it? Maybe @livingmine did u make it?

**Comment by livingmine** [comment]
@HaGuesto no, i settled with [this](https://github.com/Tecnativa/doodba/issues/180#issuecomment-439022565) instead, though i'd still love to have the autoreload working properly but i don't have time yet to find a way to make it works.

**Comment by Yajo** [comment]
It may be related also to the limits of watched files in your host system and/or container. For the time being, I'll tell you we're not actively investing time in improving this concrete situation, although if you get to make it work, we're open to PRs, for features and/or docs.
