### ISSUE TITLE
Error building on Fedora 29

### ISSUE THREAD

**Issue by linuxnow** [Tecnativa/doodba#195]
I'm trying to build the project and it fails in one of the early steps.
I've cloned the repo, fixed permissions  and set the env vars to no problem:

$ git clone https://github.com/Tecnativa/doodba-scaffolding.git myproject
$ cd myproject
$ ln -s devel.yaml docker-compose.yml
$ chown -R $USER:1000 odoo/auto
$ chmod -R ug+rwX odoo/auto
$ export UID GID="$(id -g $USER)" UMASK="$(umask)"

But I can't move forward:

$ docker-compose build --pull
[odoo@pau9 odoo_tecnativa]$ docker-compose build --pull
db uses an image, skipping
smtp uses an image, skipping
wdb uses an image, skipping
cdnjs_cloudflare_proxy uses an image, skipping
fonts_googleapis_proxy uses an image, skipping
fonts_gstatic_proxy uses an image, skipping
google_proxy uses an image, skipping
gravatar_proxy uses an image, skipping
Building odoo
Step 1/2 : ARG ODOO_VERSION
ERROR: Service 'odoo' failed to build: Please provide a source image with `from` prior to commit

Could be related to my docker version?
$ docker -v
Docker version 1.13.1, build accfe55-unsupported
$ docker-compose -v
docker-compose version 1.22.0, build f46880f
[odoo@pau9 odoo_tecnativa]$

Or maybe I need to configure something else which I can't figure.

I've had a look at the .env file and there's a line which I don't know what it should look like:
ODOO_IMAGE=docker.io/myuser/myproject-odoo

If I change it the error changes, so it could just be related.

Any help please?

--
Pau

**Comment by Yajo** [comment]
Your Docker version is too old, please update it.

**Comment by linuxnow** [comment]
What version do I need? This is the latest version available in Fedora

**Comment by Yajo** [comment]
Latest: https://docs.docker.com/install/linux/docker-ce/fedora/

**Comment by linuxnow** [comment]
Thank you!

**Comment by linuxnow** [comment]
That was it, now everything builds as expected.
I'll continue with my tests, thank you.

**Comment by Yajo** [comment]
Good news! Fedora's Docker is too outdated...
