### ISSUE TITLE
No module named 'OpenSSL

### ISSUE THREAD

**Issue by linuxnow** [Tecnativa/doodba#196]
I'm trying to install l10n_es_facturae and it requires OpenSSL..
So I try to add it to the requirements to no luck:

I've first tried in odoo/custom/dependencies/apt.txt
python3-openssl

Then as a pip:
pyOpenSSL

I rebuild the images:
docker-compose build --pull
docker-compose -f setup-devel.yaml run --rm odoo
docker-compose up

but I still get the message in the logs:
odoo_1                    | 2019-01-17 15:54:01,732 1 INFO ? root: No module named 'OpenSSL'
odoo_1                    | 2019-01-17 15:54:02,219 1 INFO ? root: No module named 'OpenSSL'
odoo_1                    | 2019-01-17 15:54:02,220 1 INFO ? root: No module named 'OpenSSL'

And I cannot install facturae.

What am I doing wrong?

Thanks
Pau

**Comment by linuxnow** [comment]
I'm not sure if this is the right solution but I've ended up adding it twice in apt.txt and pip.txt. And now it is there-

**Comment by Yajo** [comment]
Do not install python dependencies with apt, only with pip. The python executable found in modern images is not that from apt, but that from the official docker image in the docker hub.
