### ISSUE TITLE
Move scaffolding to Docker Swarm

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/doodba#20]
WIP of moving scaffolding to docker-compose file v3.1 and supporting only Docker Swarm (>=1.13) in `prod.yaml` can be found in https://github.com/Tecnativa/docker-odoo-base/tree/scaffolding-composefile3.

**Comment by lasley** [comment]
IMO it feels a bit early to deprecate the older compose files. This is just scaffold though, right? So really it's just a sample, and the user is free to use whatever?

**Comment by Yajo** [comment]
Yeah, [of course](https://github.com/Tecnativa/docker-odoo-base#can-i-have-my-own-scaffolding).

There's still https://github.com/docker/compose/issues/4315, and I'm also considering moving the scaffolding to make use of [ansible-container](http://docs.ansible.com/ansible-container/) instead of plain docker-compose.

Still nothing decided, but keep an eye on this issue for progress 😉

**Comment by lasley** [comment]
Ahahahah I'm so happy you guys are loving Ansible!

**Comment by Yajo** [comment]
OK, now there's a way to define different environments with v3 of docker compose file: https://github.com/moby/moby/issues/31101#issuecomment-330152093 (it was there before, I just didn't read carefully enough).

That would count as a breaking change, but allows to move for v3. [Still I'm not sure if ansible would support having v3](http://docs.ansible.com/ansible/latest/docker_service_module.html#synopsis), which is very important for us too...

**Comment by lasley** [comment]
I still think this move is quite early personally. Also, supporting only Swarm seems like cutting out a good amount of other uses out of the picture. We use Kubernetes here, and likely won't be switching any time soon. 

Ansible - yeah it uses `docker-py` if you're using the `docker` module, which isn't compatible with `docker-compose`. People on the interwebz look to be using docker shell commands when newer syntax is required.

**Comment by Yajo** [comment]
Well, switching to docker compose file v3+ does not force swarm, it just enables it. You can still use swarmless docker with that file version.

**Comment by Yajo** [comment]
Will do later in https://github.com/Tecnativa/doodba-scaffolding
