### ISSUE TITLE
How to change /opt/odoo/auto/odoo.conf content

### ISSUE THREAD

**Issue by livingmine** [Tecnativa/doodba#201]
Based on the documentation, 

> /opt/odoo/auto: The automatic one
This directory will have things that are automatically generated at build time.

we know that odoo.conf will be generated at build time. However, what is the correct way to modify its content? I thought the addons_path inside odoo.conf will reflects the content of the repos.yaml, i.e., the additional repos should be included in the addons_path. Am i missing something?

**Comment by Yajo** [comment]
Take a look to [`conf.d`](https://github.com/Tecnativa/doodba#optodoocustomconfd).

The addons path inside is autogenerated, yes. It uses `/opt/odoo/auto/addons` as the single path, where all needed addons are symlinked [according to instructions in `addons.yaml`](https://github.com/Tecnativa/doodba#optodoocustomsrcaddonsyaml) at boot time.
