### ISSUE TITLE
[QUESTION] Include private repository

### ISSUE THREAD

**Issue by HaGuesto** [Tecnativa/doodba#207]
We include a private repository consisting of different submodules in our doodba, e.g. the general structure of all OCA modules like `web` repository and `web_responsive` module.

What is the best solution to include it in the doodba? In the `private` folder? It does recognize in the `private` folder if subdirectories are modules. So, whats the best approach here?

**Comment by livingmine** [comment]
@HaGuesto [addons.yaml](https://github.com/Tecnativa/doodba#optodoocustomsrcaddonsyaml) and [repos.yaml](https://github.com/Tecnativa/doodba#optodoocustomsrcreposyaml) might be the best approach for you.

**Comment by HaGuesto** [comment]
I works fine now. Thanks @livingmine !
