### ISSUE TITLE
HowTo enable database listing? HowTo create and manage databases?

### ISSUE THREAD

**Issue by HaGuesto** [Tecnativa/doodba#211]
## Problem
I do not have the rights to access `/web/database/selector`.

![image](https://user-images.githubusercontent.com/29065125/54865619-65b7e980-4d68-11e9-8d6d-fd6309072890.png)

When I try to access the database list through the odoo shell, I'm not granted access, too.

> ERROR devel odoo.service.db: Database management functions blocked, admin disabled database listing

## Questions

- How can I enable that I can access the database manager?
- How can I duplicate or create .... databases in the command line? What are the doodba commands?
- What is the best practice here?
- Is it connected to #74 

## my configuration

> ### Odoo
> ODOO_MAJOR=11
> ODOO_MINOR=11.0
> INITIAL_LANG=
> ODOO_IMAGE=docker.io/myuser/myproject-odoo
> 
> ### XXX Critical for security!!!
> ODOO_ADMIN_PASSWORD=admin
> ### XXX Get this with `htpasswd -nbB $DB_USER $ODOO_ADMIN_PASSWORD` (copy only from the colon)
> ODOO_ADMIN_PASSWORD_BCRYPT=$2y$05$B1H3F1t867/cjuHklJBpJe5vxaD40qjWMINNL71rNyBuWzIxHM.2C
> ODOO_PROXY_MODE=true
> 
> ### Domains
> DOMAIN_TEST=test.example.com
> DOMAIN_PROD=www.example.com
> DOMAIN_PROD_ALT=example.com
> 
> ### Database
> DB_VERSION=10
> DB_USER=odoo
> DB_PASSWORD=odoopassword
> DB_FILTER=.*
> 
> ### Real SMTP relay
> SMTP_REAL_MAILNAME=example.com
> SMTP_REAL_RELAY_HOST=smtp.example.com
> SMTP_REAL_RELAY_PORT=587
> SMTP_REAL_RELAY_USER=postmaster@example.com
> SMTP_REAL_RELAY_PASS=example password
> SMTP_REAL_CANONICAL_DOMAINS=example.com
> SMTP_REAL_NON_CANONICAL_DEFAULT=example.com
> 
> ### Backup
> BACKUP_S3_ACCESS_KEY=example key
> BACKUP_S3_SECRET_KEY=example secret
> BACKUP_S3_BUCKET=example-bkp
> BACKUP_EMAIL_FROM=backup@example.com
> BACKUP_EMAIL_TO=alerts@example.com
> BACKUP_ENCRYPT_KEY=example encryption key

**Comment by pedrobaeza** [comment]
Explanation of the why is in https://github.com/Tecnativa/doodba/issues/67#issuecomment-467339077, but right now I don't know possible environment variable for enabling it. @Yajo, can you answer? And another thing: it would be desirable to not disable this on devel mode.

**Comment by Yajo** [comment]
> * How can I enable that I can access the database manager?

See https://github.com/Tecnativa/doodba-scaffolding/pull/27.

> * How can I duplicate or create .... databases in the command line? What are the doodba commands?

I'm trying to stop adding helpers here directly because now Doodba includes https://github.com/acsone/click-odoo-contrib, where you can find compatible commands for the tasks you want, and contributions there reach a wider audience.

> * What is the best practice here?

Database management is not a security problem by itself if the admin password is strong enough, and/or if it is protected by a proxy, but hiding it at least gives higher security sensation.

Adapt it to your needs, the default is to hide it though.

> * Is it connected to #74

Nope.
