### ISSUE TITLE
database not initialized

### ISSUE THREAD

**Issue by DarioLodeiros** [Tecnativa/doodba#216]
I was using a somewhat obsolete version of doodba, and now, when trying out the new one with Odoo v12, I continually encounter this problem, both in prod and devel:
![Selección_162](https://user-images.githubusercontent.com/11718836/56067652-38b19200-5d7c-11e9-8277-9efef5b69656.png)
(I downloaded doobda and only change the odoo major and odoo minor version to 12.0 to try this)
Thanks!

**Comment by Yajo** [comment]
The default database name is `prod` now. Maybe you were using an older scaffolding where https://github.com/Tecnativa/doodba/issues/67#issuecomment-458881087 still didn't land.

You should subscribe to #67 if you use Doodba.

Also, don't forget that you need to update git code (in devel) and rebuild the image (in any environment) when you switch the version.

I think it must be some of these, so I close. Reopen if needed. :wink:

**Comment by DarioLodeiros** [comment]
I think that is not the problem...
![imagen](https://user-images.githubusercontent.com/11718836/56118084-dd44f700-5f69-11e9-8d1c-4d02f9c1f6bb.png)
This is a prod enviroment, new server, new scaffolding... from last week, without any change other than version 12.0 in .env
But... 
![Selección_175](https://user-images.githubusercontent.com/11718836/56118258-2e54eb00-5f6a-11e9-8254-af5c0600b856.png)
I tried to isolate the deployment to make sure it was not a problem in my environment ... I do not know if I miss something.
Thanks Jairo!

**Comment by Yajo** [comment]
Then possibly odoo disabled the autoinitialization of database in v12. Just do what the log suggests:

    docker-compose run --rm odoo odoo -i base

**Comment by DarioLodeiros** [comment]
Ok! Of course, I just wanted to know if I was missing something important ;)
Thanks!!
