### ISSUE TITLE
doodba requires permissions for "others" in development

### ISSUE THREAD

**Issue by ap-wtioit** [Tecnativa/doodba#220]
Because the base image is always created with an odoo user that has uid=1000 and gid=1000 one needs to share the files in odoo/auto with group 1000 (see https://github.com/Tecnativa/doodba#scaffolding).

If a user does not allow his files to be read by others (e.g. chmod o-rwx odoo/custom/src/odoo, or an UMASK that doesn't grant read permissions to others) then odoo is not startable (and no addons are linked inside the container). Which essentially makes doodba require to give permissions to "others" to read the users files in development.

Could we remove the need for the hardcoded group id 1000 and user id 1000 in all environments and the required permissions for others in development?

We have patched the need for those ids and permissions away in our version but the solution is a bit bulky and not as elegant as i would like.

**Comment by Yajo** [comment]
It seems like all of our devs happen to have uid 1000 in their laptops, so we didn't hit this issue, but it absolutely makes sense.

Do you have any ideas on how to fix it? :thinking:

**Comment by ap-wtioit** [comment]
I'm creating a pull request to show you what i've done/tried so far (as i said i do not think its ideal yet)

**Comment by Yajo** [comment]
Have you tried setting the uid in the container directly?

Just add `user: 1001` to the `odoo` service in `devel.yaml` in your scaffolding. See the docs: https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources

Would that work fine?

**Comment by ap-wtioit** [comment]
I tested adding `user: ${UID:-1000}` to devel.yaml and also needed to change `chown -R root:odoo /opt/odoo` into `chown -R odoo:odoo /opt/odoo` (otherwhise i get an error on start the chdir into /opt/odoo is not possible), but the volume (/var/lib/odoo) was still mounted with 1000:1000 (when i removed the https://github.com/Tecnativa/doodba/blob/d1cd5ad6da33953f0c312535d3f6b29e4a0866f5/entrypoint.d/00-fix-volume-permissions)

the `user: ` docker-compose option only seems to affect the uid of the user used to start the container not the mounted volumes permission

**Comment by Yajo** [comment]
Hmm I'm thinking on another possible solution, but I'd need this: please provide the full logs when running [the first bash code snippet from here](https://github.com/Tecnativa/doodba#skip-the-boring-parts).

Then provide also the container booting logs: `docker-compose logs odoo`

**Comment by ap-wtioit** [comment]
Here are the outputs:

Original doobda without root permissions: https://support.wt-io-it.at/owncloud/s/3mNReby8Tz4WPdB
* `chown -R $USER:1000 odoo/auto` fails without sudo (at least on Ubuntu 18.04 LTS)
* entrypoint.d/40-addons-link then fails 

I'll upload the other runs (with sudo and my patch) as soon as they are done

**Comment by Yajo** [comment]
OK, so AFAICS the main problem is that **the odoo user in the container and your user in the host must share the same UID**. Otherwise, one of these situations mighthappen:

1. Odoo user cannot read sources.
1. Host user cannot read sources.

So, the fix is:

1. Add a `ONBUILD ARG UID=1000` to dockerfiles, so users can choose the UID at subimage build time. The default value of 1000 should make it backwards compatible.
1. Remove all the user creation and chown instructions from the main dockerfile section, and move them to the `ONBUILD` section, after that's done.
1. Add to the devel environment the corresponding build arg.

That should do the trick IMHO. You shouldn't need then any chowns on entrypoint.

**Comment by ap-wtioit** [comment]
I tested the approach with `ONBUILD` but that still had issues for me:
```
odoo_1                    | 2019-05-13 07:58:16,986 1 INFO ? odoo: Odoo version 12.0 
odoo_1                    | 2019-05-13 07:58:16,987 1 INFO ? odoo: Using configuration file at /opt/odoo/auto/odoo.conf 
odoo_1                    | 2019-05-13 07:58:16,987 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/opt/odoo/auto/addons', '/opt/odoo/custom/src/odoo/odoo/addons'] 
odoo_1                    | 2019-05-13 07:58:16,987 1 INFO ? odoo: database: odoo@db:5432 
odoo_1                    | 2019-05-13 07:58:17,441 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
odoo_1                    | 2019-05-13 07:58:17,785 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
odoo_1                    | 2019-05-13 07:58:17,785 1 INFO ? odoo.service.server: Watching addons folder /opt/odoo/auto/addons 
odoo_1                    | 2019-05-13 07:58:17,785 1 INFO ? odoo.service.server: Watching addons folder /opt/odoo/custom/src/odoo/odoo/addons 
odoo_1                    | 2019-05-13 07:58:17,798 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
odoo_1                    | 2019-05-13 07:58:17,807 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on example.com:8069 
odoo_1                    | 2019-05-13 07:58:17,815 1 ERROR ? odoo.modules.loading: Database devel not initialized, you can force it with `-i base` 
odoo_1                    | 2019-05-13 07:58:19,864 1 INFO ? odoo.http: HTTP Configuring static files 
odoo_1                    | 2019-05-13 07:58:19,884 1 INFO devel werkzeug: 172.125.60.75 - - [13/May/2019 07:58:19] "GET /web/login HTTP/1.1" 500 - 2 0.003 0.014
odoo_1                    | Traceback (most recent call last):
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 128, in application
odoo_1                    |     return application_unproxied(environ, start_response)
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
odoo_1                    |     result = odoo.http.root(environ, start_response)
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1318, in __call__
odoo_1                    |     return self.dispatch(environ, start_response)
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1291, in __call__
odoo_1                    |     return self.app(environ, start_wrapped)
odoo_1                    |   File "/home/odoo/.local/lib/python3.5/site-packages/werkzeug/wsgi.py", line 766, in __call__
odoo_1                    |     return self.app(environ, start_response)
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1471, in dispatch
odoo_1                    |     ir_http = request.registry['ir.http']
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 176, in __getitem__
odoo_1                    |     return self.models[model_name]
odoo_1                    | KeyError: 'ir.http'
odoo_1                    | 2019-05-13 07:58:19,933 1 INFO ? werkzeug: 172.125.60.75 - - [13/May/2019 07:58:19] "GET /web/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 - - - -
odoo_1                    | 2019-05-13 07:58:19,937 1 INFO ? werkzeug: 172.125.60.75 - - [13/May/2019 07:58:19] "GET /web/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 - - - -
odoo_1                    | 2019-05-13 07:58:19,937 1 INFO ? werkzeug: 172.125.60.75 - - [13/May/2019 07:58:19] "GET /web/login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 - - - -
odoo_1                    | 2019-05-13 07:58:20,000 1 INFO ? werkzeug: 172.125.60.75 - - [13/May/2019 07:58:20] "GET /web/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - - - -
```
Even when the odoo user has the correct permissions now (as far as i could check)

Current sourcecode is here: https://github.com/ap-wtioit/docker-odoo-base/tree/master-enable_other_uids_2
for scaffolding in devel.yaml i added
```
                UID: "${UID:-1000}"
                GID: "${GID:-1000}"
```
to odoo build args
and `user: "${UID:-1000}"` to odoo service

will update the status here when i have time again this week

**Comment by ap-wtioit** [comment]
I think i solved the issue with:
https://github.com/Tecnativa/doodba/pull/224
https://github.com/Tecnativa/doodba-scaffolding/pull/35
