### ISSUE TITLE
ERROR: Network

### ISSUE THREAD

**Issue by mokerosan** [Tecnativa/doodba#222]
I have the following problem, when I try to launch the prod.yaml "docker-compose -f prod.yaml up --build --remove-orphans" I get the following error **"ERROR: Network" myproject_default "needs to be recreated - option "encrypted" has changed"**.
I'm in my local machine is it possible to launch the template prod.yaml and traefik in local? to perform tests obviously.

**Comment by pedrobaeza** [comment]
You have changed your configuration file, so you need to down entire instances running and up again. Do that.
