### ISSUE TITLE
Key (name)=(English) already exists.

### ISSUE THREAD

**Issue by mokerosan** [Tecnativa/doodba#223]
is a clean installation following the instructions of the repo tutorial
when I try to create a new database within the devel project, I get the following error
[the log is too long so I leave it on this link](https://paste.ofcode.org/3EKiFDV6PeEBVqhnxJjPyz)

SO : Fedora
Docker: Docker version 18.09.6, build 481bc77
Docker-Compose: Docker version 18.09.6, build 481bc77

**Comment by pedrobaeza** [comment]
This has nothing to do with Doodba itself, but how are you using it. It seems you have tried to create a new DB over an existing one. You don't need to do that, as the DB is already auto-created, and it's called `devel`.
