### ISSUE TITLE
Tests might not be stable

### ISSUE THREAD

**Issue by ap-wtioit** [Tecnativa/doodba#229]
When https://github.com/Tecnativa/doodba/pull/227 was merged our internal gitlab CI failed the build for the automatic upstream merge request with these errors (on Odoo 10.0 11.0 and 12.0):
```
======================================================================
FAIL: test_addons_filtered (tests.ScaffoldingCase) (DBNAME='prod', DB_VERSION='10', ODOO_MINOR='12.0-9661', PWD='/home/gitlab-runner/builds/0e5c5655/0/orpheus/docker-odoo-base/tests/scaffoldings/dotd')
Test addons filtering with ``ONLY`` keyword in ``addons.yaml``.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/0e5c5655/0/orpheus/docker-odoo-base/tests/__init__.py", line 78, in compose_test
    env=full_env,
  File "/home/gitlab-runner/builds/0e5c5655/0/orpheus/docker-odoo-base/tests/__init__.py", line 51, in popen
    self.assertFalse(Popen(*args, **kwargs).wait())
AssertionError: 1 is not false

----------------------------------------------------------------------
Ran 1 test in 0.402s

FAILED (failures=1)
```
this was including the eslint commit https://github.com/Tecnativa/doodba/pull/227/commits/4a9bea50817be3f8bb12c9ee1e154e126d4f67f6
that was done after travis CI failed the build for the merge request here on github

Also https://github.com/Tecnativa/doodba/pull/228 has the same errors in the builds https://travis-ci.org/Tecnativa/doodba/jobs/558202240, https://travis-ci.org/Tecnativa/doodba/jobs/558202239 although that might not include the eslint change

i will update the issue once i discover more on this

**Comment by ap-wtioit** [comment]
Ok currently it seems this is an issue with our CI only

**Comment by Yajo** [comment]
Possibly it was https://github.com/Tecnativa/doodba/issues/67#issuecomment-512710437, we introduced an unexpected regression, but it's not so hard to fix. Sorry for that!
