### ISSUE TITLE
Variable undefined

### ISSUE THREAD

**Issue by amon-ra** [Tecnativa/doodba#233]
Variable repo is undefined in this context:

https://github.com/Tecnativa/doodba/blob/c58b01d382c6f16acfb91ce16c5bc300ccb008f3/lib/doodbalib/__init__.py#L109

I do not know the information needed to debug in this function, maybe it could be fixed only deleting the line.

**Comment by pedrobaeza** [comment]
Although it's true seeing code, how do you get to that problem?

**Comment by ap-wtioit** [comment]
having a short look, theoretically this should happen if reading addons.yaml is not readable (permission problem?). python would then throw an IOError and repo would not be defined yet.

**Comment by pedrobaeza** [comment]
Well, I'm not sure if covering this problem initializing the variable should help to detect the permissions problem...

**Comment by ap-wtioit** [comment]
Ok i could not produce the error in practice (while waiting for some tests) by:
* setting wrong permissions for addons.yaml (it is just ignored in this case)
* adding syntax errors to addons.yaml (like after a merge conflict, this triggers a yaml.scanner.ScannerError)

**Comment by pedrobaeza** [comment]
so then I'm closing this meanwhile some valid steps to reproduce the problem are provided. Thanks for the investigation, @ap-wtioit

**Comment by Yajo** [comment]
it's a typo, thanks
