### ISSUE TITLE
Unit test for custom modules doesn't works

### ISSUE THREAD

**Issue by chusamo** [Tecnativa/doodba#243]
Hello, first of all thank you for you work in this wonderfull project.
I made some test (I've checked the official structure) for my own module and I tried to run with docker.
I used docker-compose run odoo --rm odoo addons list (there aren't addons in the list)
Also I've tried with the unittest script, however All post-tested in 0s,  0 queries message appears.
Its is curious because my own tests or tests from OCA doesn't works since it works for odoo core modules.

Do you have any idea about why the test aren't loading?

Thanks again :)

**Comment by Yajo** [comment]
AFAICS you're not telling the script which addons to select. That's why it's testing nothing, probably.

Just check: `docker-compose run --rm odoo addons --help` to understand the script usage. That should help you :wink:
