### ISSUE TITLE
Error   docker-compose -f setup-devel.yaml run --rm odoo

### ISSUE THREAD

**Issue by jaiodoo** [Tecnativa/doodba#245]
Hola,
He tratado de desplegar odoo 12 con doodba. Al hacerlo lo primero que me pasa es que los contenedores que se crean cuando ejecuto docker-compose -f setup-devel.yaml run --rm odoo se quedan como si no vieran el host hospedero porque me salta un error en el gitaggregator que no puede encontrar el host github.com.
Saludos

**Comment by pedrobaeza** [comment]
Hola, no termino de entender qué significa eso de host hospedero, pero por favor indica todos los pasos dados hasta llegar al problema.

**Comment by Yajo** [comment]
Buenas, cierro hasta que tengamos la información necesaria. Un saludo.
