### ISSUE TITLE
[RFC] Add geoIP support

### ISSUE THREAD

**Issue by JordiBForgeFlow** [Tecnativa/doodba#253]
If you a website with customers coming from various countries, you might want to propose a different pricelist for your shop depending on the country of the visitor. 

Odoo supports this, provided that the user's requests contains geolocalization data.  That is, if the geoip parameter of session is set. NGINX, for example, provides the geoip module http://nginx.org/en/docs/http/ngx_http_geoip_module.html that will add geolocalization parameters to the vistitor's request that I assume Odoo is able to use afterwards.

As this feature would be quite interesting for any company running the ecommerce in odoo, I think that it would be interesting if Doodba could provide support for this feature.

**Comment by Yajo** [comment]
It seems interesting, although we have to evaluate if it is in doodba's scope.

Could you point to the Odoo code that handles this, to see what requirements does it have?

**Comment by ap-wtioit** [comment]
Sorry just saw this. Still i wanted to document a half way working approach.

We had geiop support in one of our images by adding the following to the fork of doodba-scaffolding:
odoo/custom/build.d/900-geoip:
```
#!/usr/bin/env bash
# GeoLite2 licensed under the terms of  CC BY-SA 4.0 https://dev.maxmind.com/geoip/geoip2/geolite2/ https://creativecommons.org/licenses/by-sa/4.0/
# This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com
mkdir geoip &&
cd geoip &&
wget -q https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz &&
tar -xzf GeoLite2-City.tar.gz &&
mv */GeoLite2-City.mmdb . &&
mv */LICENSE.txt . &&
rm GeoLite2-City.tar.gz &&
rm -Rf GeoLite2-City_* &&
chown odoo:odoo GeoLite2-City.mmdb
```
odoo/custom/conf.d/geoip.conf
```
[options]
# GeoLite2 licensed under the terms of CC BY-SA 4.0 https://dev.maxmind.com/geoip/geoip2/geolite2/ https://creativecommons.org/licenses/by-sa/4.0/
# This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com
geoip_database=/opt/odoo/geoip/GeoLite2-City.mmdb
```
custom Dockerfile to add a label fullfilling the license requirement of mentioning that the image includes geoip even if its downloaded from a docker repo
```
ARG ODOO_VERSION
FROM ...:${ODOO_VERSION}-onbuild
LABEL com.example.notice_geoip="This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com. Licensed under CC-BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/."
```

But as of 2019-12-30 the new data is no longer licensable under CC-BY-SA 4.0 as they changed their license: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
Which i think makes it no longer compatible with Open Source.

We changed our script to no longer wget the file from maxmind directly but use the last version we got under CC-BY-SA 4.0

**Comment by Yajo** [comment]
Is there a way to download the file via some API?

Could we add the license key as a build arg and let downstream users supply that key in their CI pipelines to build images with builtin geoip databases?

**Comment by ap-wtioit** [comment]
According to the developer documentation: https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads
I think this should work: `https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${YOUR_LICENSE_KEY}&suffix=tar.gz`

**Comment by Yajo** [comment]
Nice! Do you feel like adding that PR?

**Comment by ap-wtioit** [comment]
yes i'll provide a PR this week.

**Comment by Yajo** [comment]
Doodba with the plumbing stuff.

Then doodba-scaffolding with the variables. As these would be secrets, we'd have to outsource them in a separate .env file if possible (although I think it won't be; then the build script will have to supply the secret in an env variable).
