### ISSUE TITLE
python3-lasso dependency not working

### ISSUE THREAD

**Issue by agenterp** [Tecnativa/doodba#257]
Hello, we try to install the python3-lasso library into our doodba image.
The problem is that it's available from apt only. 

https://packages.debian.org/sid/python3-lasso
 
If we open a console and try to import via ipython3 import lasso it will not work.

Any suggestions how wer can solve this issue?

**Comment by pedrobaeza** [comment]
Add in https://github.com/Tecnativa/doodba-scaffolding/blob/master/odoo/custom/dependencies/apt.txt any Debian package you want to have installed in your image.

**Comment by agentdeu** [comment]
@pedrobaeza 
We added this already in the apt.txt and the python3-lasso package is installed but it is not available in the python3 Version which is been used by odoo.

This is the output after the build...
```root@example:/opt/odoo# python3.5m
Python 3.5.9 (default, Nov 23 2019, 07:24:20) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lasso
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'lasso'
>>> exit()
root@example:/opt/odoo# python3m
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lasso
>>> ```

**Comment by pedrobaeza** [comment]
OK, I see, I reopen and let my colleague @Yajo to answer that knows this better.

**Comment by agenterp** [comment]
Thank You very much

**Comment by agentdeu** [comment]
@Yajo We have a workaround with an build.d script
`#!/bin/bash
set -e
log INFO Copy Python3 dist-packages
cp -R /usr/lib/python3/dist-packages/* /usr/local/lib/python3.5/site-packages`

**Comment by Yajo** [comment]
I guess you could try to install without all the dependencies: https://askubuntu.com/a/80794/546142

Also you could try to install from source: https://repos.entrouvert.org/lasso.git/tree/INSTALL

In any case, this is a very corner case that seems it cannot be fixed with any of the built-in installers, so whatever solution you use must go through a `build.d` script as you have already guessed, where you can put any instructions you want.

Regards.
