### ISSUE TITLE
conf.d in doodba-scaffolding is not usable?

### ISSUE THREAD

**Issue by yelizariev** [Tecnativa/doodba#265]
It seems that config is generated on the first run and not updated anymore.

https://github.com/Tecnativa/doodba/blob/604e358df8926404a1605c131aaa2ab7a08968a3/entrypoint.d/50-config-generate#L3-L8

 So, if I update ``odoo/custom/conf.d``, the changes are not applied. 
Is it a bug or a design decision?

**Comment by yelizariev** [comment]
ok, it does work after ``docker-compose down``

**Comment by Yajo** [comment]
>  Is it a bug or a design decision?

It's a design decision. It's only generated the 1st time. If you want to skip that system, you can generate it differently in a prior entrypoint.d script.
