### ISSUE TITLE
migrate to traefik 2.1+

### ISSUE THREAD

**Issue by yelizariev** [Tecnativa/doodba#271]
Would be great to have the following traefik features:

* Custom error pages (e.g. when odoo is starting): https://docs.traefik.io/middlewares/errorpages/
* Limit request size https://docs.traefik.io/middlewares/buffering/
* Limit request rate https://docs.traefik.io/middlewares/ratelimit/

As I understand, those features are available in traefik 2+ only

Migration docs: https://docs.traefik.io/migration/v1-to-v2/

I plan to work on this myself, but not sure when

**Comment by Yajo** [comment]
I had this on my roadmap since long too, but it's quite breaking and still didn't have time to investigate; thanks for the links.



> I plan to work on this myself, but not sure when

Thanks! That'd be awesome :blush:

**Comment by joao-p-marques** [comment]
This has been implemented in https://github.com/Tecnativa/doodba-copier-template apart from the error pages. They can be easily implemented with a middleware or another Traefik rule with a lower priority and a cathall rule to replace the standard Traefik 404 (see https://github.com/traefik/traefik/issues/1077#issuecomment-380564020)
