### ISSUE TITLE
Readme's TOC

### ISSUE THREAD

**Issue by yelizariev** [Tecnativa/doodba#280]
@Yajo @pedrobaeza 
What do you think about adding TOC?

Example: https://github.com/yelizariev/doodba/blob/toc/README.md (*doctoc* doesn't generated all links properly, I hope it will be fixed soon)

I also made a Github Actions to regenerate TOC: https://github.com/yelizariev/doodba/blob/toc/.github/workflows/doctoc.yml

**Comment by pedrobaeza** [comment]
Yeah, it can be a good addition. What I don't like is to manually regenerate it. Can this be automated after each commit?

**Comment by yelizariev** [comment]
Yes, Github Actions can do it

**Comment by Yajo** [comment]
I like it, although I'd prefer a pre-commit action instead if possible.

**Comment by yelizariev** [comment]
I'd postpone this, cause doctoc is hardly maintained and I don't think [the issue](https://github.com/thlorenz/doctoc/issues/176) will be fixed soon.

**Comment by Yajo** [comment]
There are plenty of projects that do the same: https://github.com/topics/markdown-toc

Check this out, for example: https://github.com/trussworks/pre-commit-hooks#markdown-toc

**Comment by yelizariev** [comment]
I just checked, that tool has the same issue: https://github.com/jonschlinkert/markdown-toc/issues/158

**Comment by yelizariev** [comment]
What do you think about deleting links from headers? The links do text laconic, but may worsen UX. Especially after adding to TOC. 

Imagine we have working TOC

![screenshot-github com-2020 02 04-12_59_37](https://user-images.githubusercontent.com/186131/73724941-3cb90100-474e-11ea-8e89-94a007bca13c.png)

User clicks ``nano`` it and sees ``link`` nano again

![screenshot-github com-2020 02 04-13_00_37](https://user-images.githubusercontent.com/186131/73724994-58bca280-474e-11ea-99c3-109bf665878a.png)

But it has a different meaning here, which is confusing

**Comment by yelizariev** [comment]
README with deleted links: https://github.com/Tecnativa/doodba/blob/c754ab562b5fe05dacb4d8830b333d823e9a0f35/README.md

Commit: https://github.com/Tecnativa/doodba/pull/286/commits/c754ab562b5fe05dacb4d8830b333d823e9a0f35

**Comment by yelizariev** [comment]
Hmm, actually, there is another workaround: use direct links in headers

**Comment by yelizariev** [comment]
Well, not really. It fixes only in case when an entire header is a link

**Comment by Yajo** [comment]
I wouldn't have a problem in removing links from headers if it's for the better.
