### ISSUE TITLE
Use doodba locally for dev purpose - Performance issue

### ISSUE THREAD

**Issue by tfossoul** [Tecnativa/doodba#291]
Hi,

I discover Doodba some weeks ago and I really like the project.
It could allow us to use the same environnement in production, staging and locally for dev purpose and all of it in docker. So I'm currently testing it..

I am just a bit bothered about the time odoo need to be available when you start it via docker-compose on my local environnement. 
When I use docker odoo need between 15-20 seconds to be available on browser and when I launch odoo via a standard way (a buildout for instance) it need between 6-10 sec.

Can I do something to make it run faster locally (start, stop, restart, install and update module) ? Am I using Doodba correctly locally or does I need to use other command ?
Are you guys using doodle locally for development purpose ?

I am a neophyte with docker so maybe my question could be stupid or I could miss something obvious...

My config:
  Mac OS Mojave, 
  Docker resources: 6cpu, 5gb, 1.5gb swap.

Here are the track:
15sec

`
docker-compose -f devel.yaml up
Starting coo_doodba_db_1 ... done
Starting coo_doodba_odoo_1 ... done
Starting coo_doodba_odoo_proxy_1 ... done
Attaching to coo_doodba_db_1, coo_doodba_odoo_1, coo_doodba_odoo_proxy_1
db_1          | 
db_1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1          | 
odoo_1        | doodba INFO: Waiting until postgres is listening at db...
db_1          | 2020-02-11 09:32:**54**.131 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432

…

odoo_1        | 2020-02-11 09:33:09,281 1 INFO coo1 werkzeug: 172.18.0.4 - - [11/Feb/2020 09:33:09] "POST /web/action/load HTTP/1.1" 200 - 49 0.056 0.045
odoo_1        | 2020-02-11 09:33:**09**,520 1 INFO coo1 werkzeug: 172.18.0.4 - - [11/Feb/2020 09:33:09] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 - 97 0.080 0.143
`

When I launch odoo via a buildout env way:
9sec
`2020-02-11 09:54:**16**,780 68183 INFO ? odoo: Odoo version 12.0

…

2020-02-11 09:54:25,416 68183 INFO hap werkzeug: 127.0.0.1 - - [11/Feb/2020 09:54:25] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 304 - 15 0.010 0.013
2020-02-11 09:54:**25**,420 68183 INFO hap werkzeug: 127.0.0.1 - - [11/Feb/2020 09:54:25] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 - 2 0.003 0.012
`

Thanks in advance for the answer :)

Tom

**Comment by Yajo** [comment]
>  When I use docker odoo need between 15-20 seconds to be available on browser and when I launch odoo via a standard way (a buildout for instance) it need between 6-10 sec.

Odoo itself takes much less.

When you do `docker-compose up` it starts all the services odoo needs before starting odoo. That includes mail relay and db for example. But try this:

```bash
# First I remove containers to reset counters
➤ docker-compose down
Stopping doodba-devel-120_odoo_proxy_1             ... done
Stopping doodba-devel-120_odoo_1                   ... done
Stopping doodba-devel-120_wdb_1                    ... done
Stopping doodba-devel-120_gravatar_proxy_1         ... done
Stopping doodba-devel-120_fonts_gstatic_proxy_1    ... done
Stopping doodba-devel-120_fonts_googleapis_proxy_1 ... done
Stopping doodba-devel-120_cdnjs_cloudflare_proxy_1 ... done
Stopping doodba-devel-120_db_1                     ... done
Stopping doodba-devel-120_google_proxy_1           ... done
Stopping doodba-devel-120_smtp_1                   ... done
Removing doodba-devel-120_odoo_proxy_1             ... done
Removing doodba-devel-120_odoo_1                   ... done
Removing doodba-devel-120_wdb_1                    ... done
Removing doodba-devel-120_gravatar_proxy_1         ... done
Removing doodba-devel-120_fonts_gstatic_proxy_1    ... done
Removing doodba-devel-120_fonts_googleapis_proxy_1 ... done
Removing doodba-devel-120_cdnjs_cloudflare_proxy_1 ... done
Removing doodba-devel-120_db_1                     ... done
Removing doodba-devel-120_google_proxy_1           ... done
Removing doodba-devel-120_smtp_1                   ... done
Removing network doodba-devel-120_default
Removing network doodba-devel-120_public

# Now I start all odoo dependencies and odoo itself:
➤ time docker-compose up -d
Creating network "doodba-devel-120_default" with the default driver
Creating network "doodba-devel-120_public" with the default driver
Creating doodba-devel-120_fonts_googleapis_proxy_1 ... done
Creating doodba-devel-120_smtp_1                   ... done
Creating doodba-devel-120_fonts_gstatic_proxy_1    ... done
Creating doodba-devel-120_cdnjs_cloudflare_proxy_1 ... done
Creating doodba-devel-120_gravatar_proxy_1         ... done
Creating doodba-devel-120_db_1                     ... done
Creating doodba-devel-120_wdb_1                    ... done
Creating doodba-devel-120_google_proxy_1           ... done
Creating doodba-devel-120_odoo_1                   ... done
Creating doodba-devel-120_odoo_proxy_1             ... done
0.90user 0.08system 0:04.89elapsed 20%CPU (0avgtext+0avgdata 46584maxresident)k
0inputs+0outputs (0major+16108minor)pagefaults 0swaps

# You saw that was just ~5s. You should probably buy a faster computer...

# Now, the time to restart odoo itself:
➤ time docker-compose restart odoo
Restarting doodba-devel-120_odoo_1 ... done
0.56user 0.05system 0:02.81elapsed 21%CPU (0avgtext+0avgdata 45332maxresident)k
0inputs+0outputs (0major+15670minor)pagefaults 0swaps

# Just 2.81s
```



>  Are you guys using doodle locally for development purpose ?

Nope. Actually I don't know what is it.

**Comment by tfossoul** [comment]
➜  time docker-compose up -d
Starting coo_doodba_db_1 ... done
Starting coo_doodba_odoo_1 ... done
Starting coo_doodba_odoo_proxy_1 ... done
docker-compose up -d  0.45s user 0.13s system 24% cpu 2.375 total

coo_doodba git:(coo-21-38) ✗ time docker-compose restart odoo   
Restarting coo_doodba_odoo_1 ... done
docker-compose restart odoo  0.40s user 0.12s system 36% cpu 1.407 total


Are you guys using doodle locally for development purpose ?
**doodba***

Ok docker restart odoo faster but your browser odoo page need more time before beeing available. That is the thing I monitored with the odoo logs.
If you double the time you need before checking your result on your odoo webpage you're gonna loose time when you are developping.

**Comment by pedrobaeza** [comment]
There should be something in your end (maybe Mac...), but I don't need that time for having it enabled on my browser. It takes 3-4 seconds more for first environment loading of Odoo when the first request is done (this is the same on Odoo deployed via other ways). Try with a newer Docker version.

**Comment by tfossoul** [comment]
Ok i'll do more tests, thanks for you answers guys :)

**Comment by Yajo** [comment]
If you find a way to improve boot time, PRs are welcome!
