### ISSUE TITLE
Question About Doodba + Direct Print

### ISSUE THREAD

**Issue by agenterp** [Tecnativa/doodba#293]
Hi Doodba Team,

great work so far!

We have one project where we are planing to use direct print with this module:

https://github.com/OCA/report-print-send/tree/12.0/base_report_to_printer

now our question is, what you suggest how to use it.

Shall we install CUPS in the DOODBA Machine?

Or a dedicated DOCKER with CUPS? But then the question is how the module would work ? Do you have any experience or idea what is the best way?

**Comment by agenterp** [comment]
https://github.com/OCA/report-print-send/blob/11.0/base_report_to_printer/models/printing_server.py

**Comment by pedrobaeza** [comment]
Is it solved?

**Comment by agenterp** [comment]
@pedrobaeza yes it's perfect with the dedictaed cups server.

**Comment by pedrobaeza** [comment]
OK, yes, it's something totally outside of Odoo/Doodba, and it depends on your system architecture.
