### ISSUE TITLE
[Question] Workflow for WIP/updating modules pulled in from repos.yaml

### ISSUE THREAD

**Issue by theangryangel** [Tecnativa/doodba#299]
Hi,

Sorry for more questions. I think, hopefully, these are last :) I'm fleshing out the workflow alterations from our existing setup and setting up an internal project to really give Doodba a try out.

When we're working on a WIP module there'll be a degree of human testing/playing/iteration to experiment with things and its handy to be able to push/pull from a testing project/the project thats driven the creation/modification (i.e. the Doodba project). 

In this scenario the best option I've come up with is either;

1. Checkout that branch properly and push/pull as normal (if it's currently a private repo we're pulling in and using deployment keys in the repo adding a git config insteadOf and push/pull seems like my only option)
2. The work is done out of the Doodba project and then we have to keep running aggregate (which is super janky)

Am I missing another option thats easier/better?Does anyone have any advice on how they do this? Submodules make this easy, but I'm trying hard to stick with git-aggregator so I can keep using the features it brings. 

I suppose the other question is ensuring devs have the correct version of a repo from repos.yaml. Is the expectation that the workflow is to call aggregate every day? I can see issues arising where a dev doesn't do it and is missing a backport or has a broken backport and wastes time, etc. or they do it, and they end up wiping out whatever they were working on because it wasn't pushed to origin yet

**Comment by Yajo** [comment]
I don't understand your question fine. Are you worried about how to develop an addon? In an external repo or inside private?

**Comment by theangryangel** [comment]
Sorry I wasn't very clear. I should have self edited before I submitted this issue :( I have 2 questions -

Scenario 1;

I have OCA/web pulled into a project via repos.yaml (i.e. `odoo/custom/src/oca-web`).

If I discover an issue that needs addressing is the correct workflow;
1. Add my fork as an additional remote to the copy cloned by git-aggregator (i.e. cd odoo/custom/src/oca-web; git remote add theangryangel ssh://git@github.com/theangryangel/web; git checkout -b fix-some-issue --track theangryangel/12.0),
2. Hack on the source until I'm happy, submit PR upstream, and then add my forked branch to repos.yaml merges until it's accepted upstream? 

Scenario 2;

There are 2 or more devs working on a Doobda project.

Dev 1 fixes an issue in an upstream project and adds a branch to merge into. Does Dev 1 need to tell the other team members that they should run `invoke git-aggregate`? As far as I can tell yes?

**Comment by theangryangel** [comment]
I think 1 is answered by the new docs at https://github.com/Tecnativa/doodba-copier-template/blob/master/docs/faq.md#how-do-i-develop-for-an-external-repo-such-as-oca, thank you so much <3

**Comment by Yajo** [comment]
Great!

Remember that you can add a PR to your `repos.yaml`, so instead of just adding your own remote and branch, it would be better to add the PR number itself. See https://github.com/Tecnativa/doodba#optodoocustomsrcreposyaml

This way, you'd embrace our PR-first strategy. This is great or FLOSS development.
