### ISSUE TITLE
[7.0] Gives Bad file descriptor

### ISSUE THREAD

**Issue by aschenkels-ictstudio** [Tecnativa/doodba#302]
Don't ask me why but I needed an OpenERP 7.0 server.

Nowadays I always use Doodba so i gived it a go. But I get the following error:

```
2020-04-21 15:16:14,840 667 ERROR ? openerp.service.workers: Worker (667) Exception occured, exiting...
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/openerp/service/workers.py", line 310, in run
    self.start()
  File "/opt/odoo/custom/src/odoo/openerp/service/workers.py", line 352, in start
    self.server = WorkerBaseWSGIServer(self.multi.app)
  File "/opt/odoo/custom/src/odoo/openerp/service/workers.py", line 358, in __init__
    werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
  File "/home/odoo/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 582, in __init__
    self.port = self.socket.getsockname()[1]
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

Do I need to do something special for OpenERP 7?

**Comment by pedrobaeza** [comment]
:scream: 

We created Doodba .Dockerfile for 7.0 for a migration from 6.1 to 12 (a bounced customer that was kept in that version before arriving to us), but we only tested it in that scenario, without doing a real service up for it to run, so we can't say too much about that.

Let's see if my colleague @Yajo has tomorrow any clue about it. If not, you'll need to investigate which can be the problem. Official support from us started in 8.0.

**Comment by aschenkels-ictstudio** [comment]
Providing some extra info:

I was running the test.yaml file. When I change this to 0 workers there is no issue. The server will run.

**Comment by Yajo** [comment]
Good that you found a workaround! :blush:

If you find a better solution, please comment it here. Also, a well tested PR might be accepted, but as you can understand, we're not going to invest time in fixing this usage scenario.

I'm sorry my friend, odoo 7 is only supported for migrations currently. :man_shrugging:

**Comment by iledarn** [comment]
The same issue is in 8.0

**Comment by iledarn** [comment]
RUN pip install -U https://github.com/pallets/werkzeug/archive/0.10.4.tar.gz
in Dockerfile
solves the problem
