### ISSUE TITLE
Question: How to launch odoo manually via bash ?

### ISSUE THREAD

**Issue by tfossoul** [Tecnativa/doodba#305]
Hi,

On my dev env, I would like to control odoo inside the container and be able to launch it, stop it,...
The purpose is to work faster by restarting odoo quickly
Is it possible ? Can someone tell me how to do this ? 

Thanks in advance

**Comment by Yajo** [comment]
Yes, you can read the docs about docker-compose, which is the tool used to manage your dev env: https://docs.docker.com/compose/
