### ISSUE TITLE
Inotify for functional hot code reloading

### ISSUE THREAD

**Issue by theangryangel** [Tecnativa/doodba#308]
Hiya,

Out of the box Doodba's hot code reloading flat out doesn't work because watchdog doesn't follow symlinks.

However Odoo does support inotify, which does follow symlinks correctly.

I've tested it in a a v12 and v13 test project and it seems to be working fine, afaik.

Would you accept a PR adding inotify to the Dockerfiles for the relevant versions of Odoo that will use it? Or was there a reason why it was excluded (too heavy, etc)?

**Comment by Yajo** [comment]
I was too lazy to dig deep on that, and I just reboot odoo when needed. :grin: 

Yes, you can add it, but please include docs on the feature. Thanks!
