### ISSUE TITLE
v8 im_chat problem

### ISSUE THREAD

**Issue by andhit-r** [Tecnativa/doodba#312]
Hi,

I have encounter problem on doodba v8 deployment. When user input chat message it freeze. After that chat window won't close (video on [https://youtu.be/le1zG9yilEY](https://youtu.be/le1zG9yilEY)).

Here is [docker-compose](https://github.com/open-synergy/doodba-scaffolding/tree/8.0-standard-aeroo) that i use. And here is docker-compose for [inverseproxy](http://inverseproxy.yaml/).

No issue reported about this. Does anyone have encounter this issue?

**Comment by Yajo** [comment]
Hello, the inverseproxy link is broken. I have seen the video, I have some questions:

1. What makes you think this is a problem of doodba?
2. What environment are you using?
3. Does that happen in other environments?
4. What module is failing?
5. Do you have relevant client-side or server-side logs?

**Comment by andhit-r** [comment]
Hi,

Here is the [inverseproxy.yaml link](https://github.com/open-synergy/docker-compose-inverseproxy). 

Based on your pointer i've done further investigation. I could not use the internal chat (im_chat) on prod environment. On devel environment internal chat works. Here is [client-side log](https://gist.github.com/andhit-r/11a8aa7b8a81a729c1535da9cc06cc07) on issue occur. 

CMIIW, i'm sure that issues not in doodba but in my doodba-scafolding or my inverseproxy. 

I will try the newest copier based docker-compose. Would you kindly point me to another inverseproxy yaml that works?

Many thanks.

**Comment by Yajo** [comment]
Which environment are you using?

**Comment by andhit-r** [comment]
Hi @Yajo. After further investigation, v8 **im_chat** module need additional configuration parameter to works. Here are [link](https://gist.github.com/andhit-r/aa1ecb203a7eb0fb5ed65708d3b5093a) to sample additional configuration. I put it under conf.d dir.

Sorry for late reply.
