### ISSUE TITLE
V12 Python 3.6?

### ISSUE THREAD

**Issue by theangryangel** [Tecnativa/doodba#317]
Currently the 12 Dockerfile is set to 3.5. I believe the Odoo 12 requirement is 3.6 for 12? 

The only reason why I’m enquiring is that since this change I think I’m seeing https://github.com/odoo/odoo/issues/20158 under v12 and Traefik 1.7 with workers enabled (upgrading is on the todo list but it’s not been done yet).

The underlying system is the same, same Traefik version, same NFS server. 

Currently the version change is the last thing I haven’t ruled out as far as I can tell. All our previous projects were on 3.7 and I can’t reproduce it on those images either.

**Comment by pedrobaeza** [comment]
No, the recommended Python version for v12 is 3.5, and is working without problems with the patch mentioned in that issue, and with both Traefif 1.x or Traefik 2.x. We revert to this version because other serious problems happen with Python 3.7 and gevent. If you provide some reproducible steps, we can trace them.

**Comment by theangryangel** [comment]
Thanks Pedro, apologies for my mistake - I just assumed from a couple of posts where Odoo were saying they were running 3.6 with 12 and made an assumption.

I appreciate knowing that you've got it working fine with a similar setup. I'll go back and double check other things. Perhaps I've focused in on https://github.com/odoo/odoo/issues/20158 too much and I'm missing something. If not I'll see if I can can come up with a repro.

**Comment by theangryangel** [comment]
Apologies for the noise. I came back to this today and took a look with fresh eyes. I had tunnel vision and was completely focusing on the wrong problem :)

**Comment by pedrobaeza** [comment]
No problem, better to warn for a possible problem, as we might be affected too.
