### ISSUE TITLE
docker-compose build --pull error, due to PG new release?

### ISSUE THREAD

**Issue by HaraldPanten** [Tecnativa/doodba#320]
@Yajo 

Once I launch "docker-compose build --pull"

An error occurs:

doodba WARNING: Not aggregating code repositories
doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/apt_build.txt
doodba INFO: Executing: ['apt-get', 'update']
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease [76.7 kB]
Get:4 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages [236 kB]
Err:4 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
  File has unexpected size (236177 != 236205). Mirror sync in progress? [IP: 217.196.149.55 80]
  Hashes of expected file:
   - Filesize:236205 [weak]
   - SHA256:6fbcc3faa054b487fde5a60032b9d7367211f7da9cf2cdbdf6affe52cf0399c2
   - SHA1:fd86b5e8275422595705f717f411df20e34cf859 [weak]
   - MD5Sum:c017fab2ab582761175e26131cfdaee6 [weak]
  Release file created at: Thu, 13 Aug 2020 13:15:33 +0000
Get:5 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:7 http://security.debian.org/debian-security buster/updates/main amd64 Packages [218 kB]
Get:8 http://deb.debian.org/debian buster-updates/main amd64 Packages [7868 B]
Fetched 8449 kB in 6s (1371 kB/s)
Reading package lists...
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages.bz2  File has unexpected size (236177 != 236205). Mirror sync in progress? [IP: 217.196.149.55 80]
   Hashes of expected file:
    - Filesize:236205 [weak]
    - SHA256:6fbcc3faa054b487fde5a60032b9d7367211f7da9cf2cdbdf6affe52cf0399c2
    - SHA1:fd86b5e8275422595705f717f411df20e34cf859 [weak]
    - MD5Sum:c017fab2ab582761175e26131cfdaee6 [weak]
   Release file created at: Thu, 13 Aug 2020 13:15:33 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
Traceback (most recent call last):
  File "/opt/odoo/common/build.d/200-dependencies", line 19, in <module>
    install(name, req_file)
  File "/usr/local/lib/python3.6/site-packages/doodbalib/installer.py", line 119, in install
    return INSTALLERS[installer](file_path).install()
  File "/usr/local/lib/python3.6/site-packages/doodbalib/installer.py", line 85, in install
    self._run_command(["apt-get", "update"])
  File "/usr/local/lib/python3.6/site-packages/doodbalib/installer.py", line 22, in _run_command
    return check_call(command, shell=isinstance(command, str))
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/opt/odoo/common/build", line 32, in <module>
    subprocess.check_call(command)
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/odoo/common/build.d/200-dependencies' returned non-zero exit status 1.
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c /opt/odoo/common/build && sync' returned a non-zero code: 1

Might it be failing cause the new Posgres release?

Does it work for you?

Thanks

**Comment by pedrobaeza** [comment]
Try again in a couple of hours

**Comment by HaraldPanten** [comment]
> Try again in a couple of hours

👍

**Comment by HaraldPanten** [comment]
Closing issue. It's working again. THX Pedro
