### ISSUE TITLE
Error on Fetchmail cron

### ISSUE THREAD

**Issue by sotolucas** [Tecnativa/doodba#331]
Hi there @Yajo !
I've been experiencing this issue since I'm using doodba and I've tried a lot of things as run new and migrated databases from other servers, use production and development environments (with and without workers, with max_cron_threads set to 1 and 2) so I have no other ideas to solve this.
Seems that the Fetchmail is the only cron that is generating that error but for my surprise the mails are fetched the same...
```
odoo_1  | 2020-10-20 01:57:41,339 1 INFO eventosdistintos-erp odoo.addons.fetchmail.models.fetchmail: start checking for new emails on pop server reclamos@eventosdistintos.com
db_1    | 2020-10-20 01:57:42.600 GMT [86] ERROR:  could not obtain lock on row in relation "ir_cron"
db_1    | 2020-10-20 01:57:42.600 GMT [86] STATEMENT:  SELECT id FROM "ir_cron" WHERE id IN (4) FOR UPDATE NOWAIT
odoo_1  | 2020-10-20 01:57:42,602 1 INFO eventosdistintos-erp odoo.addons.base.ir.ir_cron: Job `Mail: Fetchmail Service` done.
```
Any clue?

**Comment by Yajo** [comment]
There's nothing specific with doodba in this regard, so AFAICS this is some Odoo bug that you have to investigate deeper and/or report to https://github.com/odoo/odoo project.
