### ISSUE TITLE
Mastering framework

### ISSUE THREAD

**Issue by crgb001** [Tecnativa/doodba#337]
I would like to master the setup and use of this whole framework. I have set it up in a local environment and play with it but I want to go further with it. Any help, advice, guide?

**Comment by Yajo** [comment]
Just do it :relaxed: 

You have docs, here and on https://github.com/Tecnativa/doodba-copier-template. Follow them carefully, and know your tools. All we do is combine some other powerful tools, but knowing them fine is the key to success.
