### ISSUE TITLE
Single Odoo instance with multiple domains with seperate database per domain.

### ISSUE THREAD

**Issue by ska-ibees** [Tecnativa/doodba#339]
Hi,

During past days I have been understanding doodba. I wanted to thank you for all the hard work done in this regard.

Now, I am planning to migrate my production server and going to adopt doodba based deployment. 

Could you please help to understand as how the same odoo instance could be used for multiple domains with separate databases?

Currently, I am using  [dbfilter_from_header](https://github.com/OCA/server-tools/tree/12.0/dbfilter_from_header) for this purpose. How can the same be achieved in doodba?

**Comment by obayit** [comment]
AFAIK you can add an array of domains to `domains_prod` inside the `.copier-answers.yaml`.

If you are using the copier template answer the `domains_prod` with a value like this:
```
[{hosts: [db1.main.com, db2.main.com]}]
```

**Comment by ska-ibees** [comment]
> 
> 
> AFAIK you can add an array of domains to `domains_prod` inside the `.copier-answers.yaml`.
> 
> If you are using the copier template answer the `domains_prod` with a value like this:
> 
> ```
> [{hosts: [db1.main.com, db2.main.com]}]
> ```
> 
> **Edit**
> Also, I would like to note that, what you mean is probably not multi instance, but multi database.
Thanks for pointin that out. I have changed issue title accordingly. 

I am still exploring doodba and trying to test it with Traefik V2. Let's see how it progess. Meanwhile, could you please share an example of single line yaml input (Which is asked during copier questions for  domains_prod and domains_test). I have tried different combinations but couldn't get it working as expected. 
Thanks again!

**Comment by obayit** [comment]
For `domains_prod` just give it `[{hosts: [db1.localhost}]`, replace db1 with the name of the production database.
My advice is to try it with Traefik v1 as described [here](https://github.com/Tecnativa/doodba-copier-template/blob/stable/docs/faq.md#how-to-bootstrap-the-global-inverse-proxy). Because v2 will probably not work so easily.

I too suffered a lot to get the production config running :( but it is definitely worth it.

**Comment by ska-ibees** [comment]
So, at what point we need to enter actual production domains? And also how can we add additional domains in future? Apparently it looks like things need to be setup during copier questions as manually editing answers file is not discouraged. 
BTW, I am able to test Traefik V2 with SSL on a live server (Single EC2 instance). Now exploring ways to deploy production image in Kubernettes (EKS).

**Comment by obayit** [comment]
Not sure about all that XD

But moving from hard install to containers is a wild ride for sure.
