### ISSUE TITLE
Multi Platform docker images

### ISSUE THREAD

**Issue by ska-ibees** [Tecnativa/doodba#342]
Is there any plan to make doodba and other assocaited images compatible with other platforms like arm etc. 
And meanwhile putting a note in the doc to specify this point. I have had hard time to implement doodba on AWS ARM and now it is even hard to maintain project on local dev (amd64 based) and production on arm64. 

By the way, even Odoo's official image is only for amd64. Is there any limitations exist with arm based platform (missing packages etc.)? Just want to ensure that arm64 would not create any bottlenecks in long run. 

![image](https://user-images.githubusercontent.com/5569632/99483887-1ec43200-2957-11eb-9690-142194d75096.png)

**Comment by theangryangel** [comment]
I'm not associated with Tecnativa, I'm just another user of Doodba, but I suspect that the official answer will be along these lines -

> By the way, even Odoo's official image is only for amd64. Is there any limitations exist with arm based platform (missing packages etc.)? Just want to ensure that arm64 would not create any bottlenecks in long run.

Out of the box Odoo (the company) doesn't support anything other than x86 or x86_64, so if you ever need to go back to them to support as soon as they find out there will be a get out of jail free card for any support question they can't/don't want to answer. If I were attempting to run a company on Odoo, right now, that would be a big concern.

Doodba generally follows Odoo's recommendations for each version, so you'll see stuff like the Doodba 12.0 image using python 3.5, etc. still. I doubt you'll see Doodba *officially* support arm until Odoo does.

That all said, from a technical stand point, it's probably do-able if you don't mind restricting it to 14.0 and using newer versions of a few libraries;

* Odoo requires a combination of the following packages. Going through that list some of the things can be installed from pip directly, some might need to be built from source.
  * https://github.com/odoo/odoo/blob/14.0/requirements.txt
  * https://github.com/odoo/odoo/blob/14.0/debian/control
* wkhtmltopdf only got arm64 support in https://github.com/wkhtmltopdf/qt/pull/45, released in 0.12.6. This is newer than 14.0 currently supports, but will probably work

**Comment by ska-ibees** [comment]
Thanks for the insightful reply. Infact, I was conviced by the higher compute power vs copute cost of new generation of AWS ARM64 EC2 instances (Graviton2 processors). Thinking of Odoo being resource intensive, idea was to have compute optimized server.
However, as arm64 is relatively new comer in the market so it could be a potiential bottleneck in the long run. As you have rightly mentioned about wkhtmltopdf. Not all packages have embraced arm64 yet. 

For this reason, I would prefer to avoid it for now. 

Meanwhile, It would be better to have this mention on Doodba's doc.

**Comment by Yajo** [comment]
wkhtmltopdf is such PITA that we cannot even have doodba based on alpine, so I wouldn't risk on ARM for the foreseeable future. Besides, Odoo is *very* resource intensive, and ARM can't compete in horsepower with x86_64 so far (it does on efficiency though) AFAIK.

So, for now this is a *nope*. However, if you want to open a PR that converts our images into multiarch ones, I wouldn't reject it personally, although support for those would be left for the community as we won't use it in production.

Closing, as there is nothing actionable to be done by our team on this regard.
