### ISSUE TITLE
[RFO] odoo_proxy connection refused while developing in mac

### ISSUE THREAD

**Issue by HaraldPanten** [Tecnativa/doodba#352]
Hi @Yajo , I'm not sure if that is an issue but a question.

First of all I know that you'll think something like: How come are you using docker in mac??!! Just do it in Linux! 😱

I would say that I'm not really a developer, so... I'm not wasting thounds of hours a day between docker-compose down/up everytime I need to work in local environment and restart 🐳

After this explanation I'd like to say that Docker seems to be slower and slower periodically. Actually it seems to load a lot while connecting to odoo proxy, see my logs:

```
odoo_proxy_1  | 2020/12/01 11:46:29 socat[19] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:46:29 socat[20] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:46:29 socat[21] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:46:59 socat[22] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:46:59 socat[23] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:46:59 socat[24] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:47:18 socat[25] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:47:18 socat[26] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:47:18 socat[27] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:48:18 socat[28] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:48:18 socat[29] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
odoo_proxy_1  | 2020/12/01 11:48:18 socat[30] E connect(5, AF=2 192.168.144.4:8069, 16): Connection refused
```

This is just a part, but I've to wait, at least 2,5 - 3 minutes everytime I restart docker; just down/up.

About one year ago, this odoo proxy loads were imperceptible... and working in mac was not that heavy (not fast but not that slow...). Do you know which changes are causing this "loading delays"? I'm using docker-compose.yml version 2.4

On the other hand I heard about docker sync. It seems to speed dockers in mac a lot. Did you hear about it?

more info: http://docker-sync.io/

THX!

**Comment by Yajo** [comment]
Yesterday https://github.com/Tecnativa/docker-whitelist/pull/3 landed. Since when have you been noticing this slowliness? If it was before that patch, try to update the image. If it was after that patch, then it might be the guilty one.

I'd be glad to fix your issue if you buy me one mac laptop :shrug:

**Comment by HaraldPanten** [comment]
> Yesterday [Tecnativa/docker-whitelist#3](https://github.com/Tecnativa/docker-whitelist/pull/3) landed. Since when have you been noticing this slowliness? If it was before that patch, try to update the image. If it was after that patch, then it might be the guilty one.
> 
> I'd be glad to fix your issue if you buy me one mac laptop 🤷

We don't mind providing one for you and fund a "doodba for mac project", optimized for its OS. Were you talking seriously? I do talk seriously... 🤔🤓

**Comment by pedrobaeza** [comment]
I'm afraid the joke of my colleague has escalated, but we can't afford to investigate other development environments different from our standard one, even with some payment, being in material or monetary one. But if anyone reading this want to catch the offer, here it is.

**Comment by HaraldPanten** [comment]
It's OK, @pedrobaeza @Yajo . No worries! 👍🏻
