### ISSUE TITLE
Error runing "invoke install -c"

### ISSUE THREAD

**Issue by cr998** [Tecnativa/doodba#375]
Al ejecutar "invoke install -c" me sale el siguiente error.

En principio el archivo "/opt/odoo/auto/odoo.conf" lo crea la propia imagen de doodba, no entiendo porque da error al intentar escribirlo

![image](https://user-images.githubusercontent.com/6900835/106046972-45cf7a80-60e3-11eb-9f0b-3ce341459697.png)

**Comment by joao-p-marques** [comment]
Indeed, that file should be automatically created by Doodba. It seems like a permission error. 

Can you check that **the file has write permissions** at least for your user and that the **Doodba container is running with the same user id as your user on the host machine**? You can pass the correct `UID`/`GID` as a build argument to docker to set the correct one.

**Comment by Tardo** [comment]
Closed due to no response received
