### ISSUE TITLE
ssh folder not in .gitignore

### ISSUE THREAD

**Issue by wildi1** [Tecnativa/doodba#376]
Hey, 
Should the odoo/custom/ssh folder not be under .gitignore ?

Because of that in Readme.md: 
"Or you could just drop the key in id_rsa and id_rsa.pub files and it should work by default without the need of adding a config file."

That would result that private keys would be commited to the repository.

Thank you

**Comment by Yajo** [comment]
Accessing a doodba repo, which defines a deployment and not just an app, requires access to all other involved repos, so granting access to it is mostly equal to granting it to all other repos it needs.

You are supposed to put there deployment keys only, which are only used for that build context and are easy to revoke either in code or in the git hosting app (gitlab, github...).

Of course, 

# NEVER PUT THERE YOUR PRIVATE KEYS
