### ISSUE TITLE
Suggestion: Replacing wdb with wdb.aiohttp

### ISSUE THREAD

**Issue by aleuffre** [Tecnativa/doodba#437]
Thanks for this amazing project, it saved me so much time and so many tears while developing on Odoo!

Apologies if this has been discussed elsewhere, I couldn't find anything related to it.

The [wdb](https://github.com/Kozea/wdb) repository seems dead, the last commit was in September 2019. It still works fine, so there's no real issue.
However, [someone else picked up the project](https://github.com/Kozea/wdb) and is continuing work on wdb, with a host of improvements. I was wondering if you would consider switching to it. There's a list of the differences/improvements from the original wdb listed in the repo's readme.

Having tested it myself, it's been just a plug and play replacement - replacing the docker image in devel.yaml and the pip install line in the dockerfile. The difference is not huge, but it seems a little nicer.

I'd be happy to try and make the PR myself if that's something you'd consider.

Thanks again for all your work!

**Comment by Yajo** [comment]
TBH I was considering just removing wdb from the stack.

These days pydevd works quite fine and with the provided debug configurations that `inv develop` produces, it's been a long time since I don't need to open wdb. Instead I can debug everything right within vscode.

Let me ask the team.

**Comment by aleuffre** [comment]
A lot of my colleagues use PyCharm and we haven't been able to make other debugging solutions work (admittedly, after getting wdb to work, we didn't spend much more time on alternatives) so we find wdb really useful and we'd be sad if it was removed.

**Comment by pedrobaeza** [comment]
Let's keep it.

**Comment by Yajo** [comment]
OK, go ahead and open the PR 😊

**Comment by aleuffre** [comment]
The wdb alternative doesn't seem to be as active as it seemed to be initially, and it has significant drawbacks. Took some time to observe the situation, but I take my recommendation/request back.
