### ISSUE TITLE
odoo.conf bug

### ISSUE THREAD

**Issue by jguenat** [Tecnativa/doodba#445]
Hello,

I have an issue with some lines in odoo.conf being maybe ignored in my testing environment.

my opt/odoo/auto/odoo.conf (inside the project_odoo_1 docker) : 
```
[options]
....
....
limit-time-cpu = 300
limit-time-real = 600
server_wide_modules = web,queue_job
workers = 2

[queue_job]
channels = root:1,root.prepare_send_print_invoice:1,root.send_print_invoice:1
```
when I start the docker, the logs show 
doodba INFO: Executing odoo --workers=2 --max-cron-threads=1
nothing about limit-time-cpu

When a lengthy cron run the following happen : 
ERROR prod odoo.service.server: WorkerCron (47) timeout after 120s

Maybe it's a recent issue, or my cron was failing for a long time. I did a docker-compose build --pull recently.

Do you have any idea why limit-time-cpu  and limit-time-real are ignored ?

Thanks for your help and for doodba :)

Julien

**Comment by Yajo** [comment]
Yes, you're naming options wrong. See https://www.odoo.com/documentation/14.0/developer/misc/other/cmdline.html#configuration-file
