### ISSUE TITLE
Odoo 16: links in addons path won't work

### ISSUE THREAD

**Issue by joao-p-marques** [Tecnativa/doodba#468]
### Discussed in https://github.com/Tecnativa/doodba/discussions/467

<div type='discussions-op-text'>

<sup>Originally posted by **yelizariev** January  3, 2022</sup>
Links to the modules won't work because of recent changes. See https://github.com/odoo/odoo/pull/82081</div>

**Comment by joao-p-marques** [comment]
Maybe we can simplify a bit to solve this issue:
- For development, instead of reading the addons from `odoo/auto`, we could read from `odoo/custom/src` (making the necessary adjustments to the `addons_path` configuration). We would loose the possibility of limiting certain addons with `addons.yaml`, but that is not that important for development.
- For production/staging environments, instead of symlinking, we can just copy the desired addons to the destination when building the image. It could even be a good opportunity to shift the approach a bit and rely on `pip` for that, as it would allow a better version management of the addons, and it is the method currently applied in OCA.

**Comment by pedrobaeza** [comment]
I would avoid always the `pip` mangling and its version managemente + addons path mangling.

**Comment by pedrobaeza** [comment]
This is finally working as is, so closing.
