### ISSUE TITLE
Translation problem in dooba odoo generated image

### ISSUE THREAD

**Issue by ceballos59** [Tecnativa/doodba#469]
## Describe the bug

After generation, some elements are translated and some are not. Image is attached. Those not translated are not two or three but many. Attached example image

With the same odoo in a normal installation outside of doodba all the labels are translated

## To Reproduce
one sample:
Odoo / Purchase / Request for quotation 

**Affected versions**:
odoo 12 CE spanish translation

**Expected behavior** All elements need to be translated

**Additional context** 
Docker version 4.3.0
Window 10 pro
WSL 2
Debian 

Sample capture
<img width="936" alt="2022-01-12 14_22_40-PO00002 - Odoo" src="https://user-images.githubusercontent.com/17497794/149159423-15250e02-3d1f-4bf1-84c1-1de4e746ef8c.png">

**Comment by HviorForgeFlow** [comment]
I guess you are running it on devel, remember by default you are using some --dev flags, I'm not 100% sure but I think the xml one as it makes to load views from files it is producing this error. 
![image](https://user-images.githubusercontent.com/32061121/149162733-4997a70c-8722-47d2-b3c3-599b303259dc.png)
Try to remove --dev command to see if error persist
Thanks!

**Comment by joao-p-marques** [comment]
Thanks for the reply @HviorForgeFlow. Indeed, that seems to be your issue @ceballos59 so I am closing this. Hope it helps!

**Comment by joao-p-marques** [comment]
Ok, first of all, you would need to recreate the containers for this change to take effect (`docker-compose up -d`) should do it. Are you sure it got recreated?

Also, are you sure you are loading the translation correctly? Make sure you override the current terms when loading it…

**Comment by pedrobaeza** [comment]
Maybe a down is needed before, or simply the terms are not translated yet, but this is not a Doodba problem.

**Comment by ceballos59** [comment]
😊😊😊
I´m sorry.You are totally right, thank you very much, after docker-compose
up all the translated tags appeared. Thanks a lot.

**Comment by macagua** [comment]
I have the same issue for Odoo 13 Community Edition, and fixed this changed 

from this config ``- --dev=reload,qweb,werkzeug,xml`` 

to this config ``- --dev=reload,qweb,werkzeug`` 

as the following example:

![command_yml](https://user-images.githubusercontent.com/185395/176818682-9c667197-bca1-4c73-831c-172f4a998aec.png)

**Comment by pedrobaeza** [comment]
@macagua that option is explicitly put in dev environment to reload XML files each time you refresh. That's a development option to ease it for not having to update your module. But you have to sacrifice in such case the translations.
