### ISSUE TITLE
Error build version 10

### ISSUE THREAD

**Issue by ValentinVinagre** [Tecnativa/doodba#470]
## Describe the bug

Failed to fetch apt.postgresql in build process.

## To Reproduce

**Affected versions**: 10

1. Build the docker.

![Selection_107](https://user-images.githubusercontent.com/22913794/150137319-451106b5-c1b0-48a1-8699-cab7c79b1dab.png)

**Comment by joao-p-marques** [comment]
Are you using https://github.com/Tecnativa/doodba-copier-template to deploy it? You must include [this fix](https://github.com/Tecnativa/doodba-copier-template/blob/main/odoo/custom/build.d/%7B%25%20if%20odoo_version%20%3C%2011%20%25%7D20-update-pg-repos%7B%25%20endif%20%25%7D.jinja) to update those APT repos.

As the doodba images are frozen and unsupported for those versions, it is better to use the doodba-copier-template support, that allows us to patch those cases...

**Comment by ValentinVinagre** [comment]
> Are you using https://github.com/Tecnativa/doodba-copier-template to deploy it? You must include [this fix](https://github.com/Tecnativa/doodba-copier-template/blob/main/odoo/custom/build.d/%7B%25%20if%20odoo_version%20%3C%2011%20%25%7D20-update-pg-repos%7B%25%20endif%20%25%7D.jinja) to update those APT repos.
> 
> As the doodba images are frozen and unsupported for those versions, it is better to use the doodba-copier-template support, that allows us to patch those cases...

Thanks 😃
