### ISSUE TITLE
Docker image label org.label-schema.build-date has wrong format

### ISSUE THREAD

**Issue by ap-wtioit** [Tecnativa/doodba#481]
## Describe the bug

The published docker images on docker.io have the wrong format in the org.label-schema.build-date label.

According to http://label-schema.org/rc1/ this should be [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) with the example given there: `org.label-schema.build-date="2016-04-12T23:20:50.52Z"`

When downloading the images from docker.io the format of the images is `"org.label-schema.build-date": "2022-02-27 00:23:14.336017516+00:00"`

The build hook here: https://github.com/Tecnativa/doodba/blob/master/hooks/build#L22 should use a format described in RFC3339

## To Reproduce

**Affected versions**:

1. pull docker image `docker pull docker.io/tecnativa/doodba:15.0`
2. inspect build_date `docker inspect --format '{{index .Config.Labels "org.label-schema.build-date"}}' docker.io/tecnativa/doodba:15.0`
3. output shows non RFC3339 date: `2022-02-27 00:23:14.336017516+00:00`

**Expected behavior** 
org.label-schema.build-date should be RFC3339

**Additional context**
the non standard build date format causes problems with other software expecting properly formated date strings.

**Comment by pedrobaeza** [comment]
Can you do the PR solving that?

**Comment by ap-wtioit** [comment]
@pedrobaeza after some more investigation `date().strip()` maps to `date --rfc-3339 ns` (should be `date --rfc-3339=ns` according to the manpage, but that's not the issue), which as the name suggests would be RFC3339. And as somebody already discussed this here https://lists.gnu.org/archive/html/bug-coreutils/2006-05/msg00014.html the space is indeed RFC3339.
> NOTE: ISO 8601 defines date and time separated by "T".
> Applications using this syntax may choose, for the sake of
> readability, to specify a full-date and full-time separated by
> (say) a space character.

So it looks like graylog parsing the date is not capable of parsing RFC3339 build dates only ISO 8601 and i have to fix that.

Therefore this is a false positive. Sorry for bugging you.

**Comment by pedrobaeza** [comment]
OK, no problem. Thanks for the explanation.
