### ISSUE TITLE
Can't install by default all addons from core odoo 14.0

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/doodba#485]
## Describe the bug

Just create a new scaffolding for Odoo 14.0 and don't restrict odoo addons. It will not install all addons if you run `docker-compose run --rm odoo addons init --installable --extra --enterprise --explicit`

**Actual behavior**

```
doodba INFO: Waiting until postgres is listening at db...
doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
doodba INFO: Generating /opt/odoo/auto/odoo.conf file. Overriding any existing...
doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
doodba INFO: Executing addons init --installable --extra --enterprise --explicit
Addons without manifest:
{'/opt/odoo/custom/src/odoo/addons/odoo_referral_portal'}
ERROR: 1
```

**Expected behavior** 

Ignore this folder, that has nothing relevant: https://github.com/odoo/odoo/tree/14.0/addons/odoo_referral_portal

**Comment by pedrobaeza** [comment]
Can you put the PR with such ignore?

**Comment by Yajo** [comment]
MVP fix in https://github.com/odoo/odoo/pull/85823

**Comment by pedrobaeza** [comment]
I suppose it's there by any weird glitch they have. The CI is red, so maybe it's showing such patch. Let's see what they say.

**Comment by MiquelRForgeFlow** [comment]
The fix in odoo was merged.
