### ISSUE TITLE
Cannot Pull doodba:12.0-onbuild Image

### ISSUE THREAD

**Issue by edipiqoni** [Tecnativa/doodba#538]
## Describe the bug

I cannot pull the doodba image anymore, pretty sure this has worked before on the same project Im working on. 

## To Reproduce

➜  docker git:(master) ✗ **docker-compose build --pull**

[+] Building 1.4s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                       0.0s
 => => transferring dockerfile: 32B                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                            0.0s
 => ERROR [internal] load metadata for ghcr.io/tecnativa/doodba:12.0-onbuild                                                                                               1.3s
 => [auth] tecnativa/doodba:pull token for ghcr.io                                                                                                                         0.0s

 > [internal] load metadata for ghcr.io/tecnativa/doodba:12.0-onbuild:

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: unexpected status: 403 Forbidden

**Expected behavior** To have the doodba image pulled 

**Additional context** Using latest docker Docker version 20.10.22, build 3a2c30b, and using a Mac M1.

**Comment by ap-wtioit** [comment]
it is working fine on our systems (linux/amd64 not arm64):
`docker pull ghcr.io/tecnativa/doodba:12.0-onbuild`
```
12.0-onbuild: Pulling from tecnativa/doodba
4f250268ed6a: Pull complete 
1b49aa113642: Pull complete 
c159512f4cc2: Pull complete 
8439168fd8dc: Pull complete 
55abbc6cc158: Pull complete 
505e2874b303: Pull complete 
e3e3b90449b1: Pull complete 
47836e9b7e25: Pull complete 
2ea565f037ec: Pull complete 
db2043132768: Pull complete 
7a0196c64ac2: Pull complete 
a1fd2a709944: Pull complete 
0f29e65ef6f2: Pull complete 
71f7733313df: Pull complete 
1741ff05a484: Pull complete 
0cfd2e53991a: Pull complete 
d7dc22720119: Pull complete 
962d75b3d9c6: Pull complete 
ffaf108d94e6: Pull complete 
79191602bd1d: Pull complete 
e8e139edacf4: Pull complete 
ba904aaf9fbc: Pull complete 
Digest: sha256:c20566bffacec0deb58334439a4646fef8b02e1707826f583a7afa614d778cec
Status: Downloaded newer image for ghcr.io/tecnativa/doodba:12.0-onbuild
ghcr.io/tecnativa/doodba:12.0-onbuild
```

Are you sure you are pulling the linux/amd64 architecture of the image? (No ARM images are provided yet, see https://github.com/Tecnativa/doodba/issues/342)

And are you sure you are not hitting the docker limits (https://docs.docker.com/docker-hub/download-rate-limit/)?

**Comment by ap-wtioit** [comment]
Yes you are correct (in a way):
```
FROM tecnativa/doodba:${ODOO_VERSION}-onbuild
```
pulls the image from dockerhub

```
FROM ghcr.io/tecnativa/doodba:${ODOO_VERSION}-onbuild
```
pulls the image from github container registry

So it really looks like (given the 403) the credentials on your system *for the github container registry* are not setup correctly.

Can you run a `docker pull ghcr.io/tecnativa/doodba:12.0-onbuild` and post the output?
