### ISSUE TITLE
Outdated images for 11.0 and 12.0

### ISSUE THREAD

**Issue by Tardo** [Tecnativa/doodba#540]
The github workflow is not building the images for 11.0 and 12.0 this gives problems. Already version 11.0 cannot be used because it is pointing to an address that does not exist and can't install postgresql-client.

I don't know if it is preferable to include these versions or to give them as "unattended" and remove the Dockerfile from the repository.

https://github.com/Tecnativa/doodba/blob/master/.github/workflows/ci.yaml#L37

**Comment by ap-wtioit** [comment]
Checked with different images (this part isn't any different in ours) and i can install postgresql-client fine:
```bash
docker run --rm --entrypoint="" -it tecnativa/doodba:12.0 bash -c 'apt-get update && apt-cache search postgres && apt-get install -y postgresql-client-10 && psql --version'
docker run --rm --entrypoint="" -it tecnativa/doodba:11.0 bash -c 'apt-get update && apt-cache search postgres && apt-get install -y postgresql-client-13 && psql --version'
docker run --rm --entrypoint="" -it ...wt-io-it.../docker-odoo-base:12.0 bash -c 'apt-get update && apt-cache search postgres && apt-get install -y postgresql-client && psql --version'
docker run --rm --entrypoint="" -it ...wt-io-it.../docker-odoo-base:11.0 bash -c 'apt-get update && apt-cache search postgres && apt-get install -y postgresql-client-12 && psql --version'
```
Our CI builds and tests our images daily, which url do you mean, and do you have a link to the failed install or at least some logs?

**Comment by ap-wtioit** [comment]
And images for 12.0 and 11.0 have been built in https://github.com/Tecnativa/doodba/pull/535

**Comment by Tardo** [comment]
Yes, I am referring to these images https://github.com/Tecnativa/doodba/pkgs/container/doodba%2Fdoodba which are the ones used by doodba-copier-template.

As far as I know, the way you indicate, you would have to relaunch this update every time the container is "down" no?

**Comment by Tardo** [comment]
My bad... I didn't see this: https://github.com/Tecnativa/doodba/blob/master/.github/workflows/ci.yaml#L42

Sorry!
