### ISSUE TITLE
Invalid signature when building

### ISSUE THREAD

**Issue by saltonmassally** [Tecnativa/doodba#542]
## Describe the bug
When attempting to build the Docker image using the latest version of the image, the following error occurs during the build process:

```
GPG error: http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease: At least one invalid signature was encountered.
E: The repository 'http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease' is not signed.
```

Do we need to add

```
RUN apt-get update && \
    apt-get install -y curl ca-certificates gnupg2 debian-archive-keyring && \
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg > /dev/null && \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    apt-get update
```

to the dockerfile?

## To Reproduce

**Affected versions**: 14.0

1. Run the docker build command using the latest version of the Docker image.
2. The build process will fail with the above error.

**Expected behavior** A clear and concise description of what you expected to happen.
The Docker image should build successfully without encountering the GPG error related to the PostgreSQL repository.

**Additional context** Add any other context about the problem here. (e.g. OS, Docker
version, ...)

**Comment by pedrobaeza** [comment]
Hi, I have just done `docker-compose build --pull` in version 14 using doodba-copier-template scaffolding and don't get such problem.

**Comment by ap-wtioit** [comment]
The signature is already with `curl -SL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -` in https://github.com/Tecnativa/doodba/blob/master/14.0.Dockerfile#L57 the errors to me look like the repo http://apt.postgresql.org/pub/repos/apt/ is not as stable as we would wish for and sometimes fails validation with the key.
And for now buster still seems fine with adding keys "the old" way so we do not need to migrate to the gpg based statements yet for adding the keys.

I also can confirm that building the images works on our CI and DEV systems.

However this seems to be the same issue we hit there:
* https://github.com/Tecnativa/doodba/pull/541#issuecomment-1461480856
* https://github.com/Tecnativa/doodba/actions/runs/4363783443/jobs/7630302273

**Comment by saltonmassally** [comment]
It works now, thank you. I had to blow away my docker images and rebuild from scratch
