### ISSUE TITLE
Excesive top margin downloading PDF documents

### ISSUE THREAD

**Issue by mfloridosygel** [Tecnativa/doodba#589]
## Describe the bug

When you download a PDF (e.g. Preview or Invoice) for the first time it appears correctly, but when you download it again, the top margin increases.

It happens using doodba-copier-template and my private projects.

Paper format is not modified, all by default.

The parameter "report.url" is correctly configurated.
![image](https://github.com/Tecnativa/doodba/assets/127136046/654fafcd-5e78-4913-aad2-d9f4a1580f47)

First download:
![image](https://github.com/Tecnativa/doodba/assets/127136046/606377c6-0f94-4fa9-aff5-37881be0b1f8)

Second download:
![image](https://github.com/Tecnativa/doodba/assets/127136046/5ca8e1f1-83d9-44b0-94f9-42966e39cc69)

## To Reproduce

I am using doodba-copier-template, choosing Odoo version "16.0" and Postgresql version '13'.

Here is my copier-answers,yml:
```
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v5.3.5
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ''
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ''
odoo_dbfilter: ^prod
odoo_initial_lang: es_ES
odoo_listdb: true
odoo_oci_image: ''
odoo_proxy: traefik
odoo_version: 16.0
paths_without_crawlers:
- /web
- /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: '13'
project_author: Tecnativa
project_license: BSL-1.0
project_name: myproject-odoo
smtp_default_from: ''
smtp_relay_host: '''
```

**Affected versions**:
It affects on version 16.0 and 17.0.

1. Command: "copier copy --trust gh:Tecnativa/doodba-copier-template project/folder".
2. Command: "invoke develop img-build git-aggregate resetdb start".
3. Activate "sale_management" module.
4. Go to "General settings" > "Companies" > "Document Layout" >  "Configure Document Layout".
5. Paper format > A4.
6. Click on "Download PDF Preview".

The first one will be correct, but the second will have an excesive top margin.

**Expected behavior**
All the downloads like the first one, with a normal top margin.

**Additional context**
Ubuntu 22.04.
Docker version 24.0.7, build afdd53b.

**Comment by HaraldPanten** [comment]
@josep-tecnativa @yajo @ap-wtioit Have you experienced anything like that?

THX

**Comment by ap-wtioit** [comment]
hm, i just tested in 16.0 with a fresh database installing account (Invoicing), we have usually no odoo_initial_lang set and use nginx instead of traefik. But yes also in our demo instance there is something strange:
![image](https://github.com/Tecnativa/doodba/assets/38032588/65b5e7b3-5c28-4273-8087-6fe7a6bddc7c)

But regardless if i keep US Letter or change it to A4 the Company Address is not visible (only the last line: United States)
![image](https://github.com/Tecnativa/doodba/assets/38032588/fb92739b-47dc-46b1-8c30-78ba087f8c98)

**Comment by josep-tecnativa** [comment]
I think that the best solution is to use 0.12.6.1 version, that is compatible with bookworm, but i have to test if it works properly. Once is tested i will do a PR in order to solve this issue.

**Comment by ap-wtioit** [comment]
@josep-tecnativa thanks.

FYI i have tested switching back to 0.12.5 and got that working (as a hotfix directly in doodba):
in odoo/Dockerfile:
```Dockerfile
ARG ODOO_VERSION
FROM ghcr.io/tecnativa/doodba:${ODOO_VERSION}-onbuild
USER root
ARG WKHTMLTOPDF_VERSION=0.12.5
ARG WKHTMLTOPDF_CHECKSUM='8feeb4d814263688d6e6fe28e03b541be5ca94f39c6e1ef8ff4c88dd8fb9443a'
RUN curl -SLo wkhtmltox.deb https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/${WKHTMLTOPDF_VERSION}/wkhtmltox_${WKHTMLTOPDF_VERSION}-1.buster_amd64.deb
RUN curl -SLo libssl1.1.deb http://deb.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
RUN dpkg -i libssl1.1.deb \
    && dpkg -i wkhtmltox.deb \
    && rm ./wkhtmltox.deb \
    && rm ./libssl1.1.deb
USER odoo
```
This is still a hotfix, but we are now testing and it looks like it fixes the issue.

Will prepare a PR as well but if you get 0.12.6.1 running that's fine as well.

**Comment by mfloridosygel** [comment]
Hello,

I just tested it and it works properly.

Thanks you all!
