### ISSUE TITLE
Cannot build doodba 10.0-onbuild

### ISSUE THREAD

**Issue by mfloridosygel** [Tecnativa/doodba#594]
Hello, 

I am trying to build doodba:10.0-onbuild image because I have a historical Odoo v.10.

I tried adding the "10-add-jessie_backport" from [this issue](https://github.com/Tecnativa/doodba/issues/544), downloading a [previous commit](https://github.com/Tecnativa/doodba/tree/20dfe8a42487ce00f8220d56e06263c296bfd6db) and I modified the Dockerfile adding:

- Archived repositories for Debian.
- Archived repositories for postgresql.
- "--force-yes" in all the apt-get install lines.

When I build the image (docker build . -t localdoodba:v10) I get this error with the bin-deprecated/install.sh file:

The following packages have unmet dependencies:
libpq-dev : Depends: libpq5 (= 14.5-1.pgdg90+1) but 9.4.26-0+deb8u1 is to be installed.

I attached the files that I am using (Dockerfile, install.sh and 100-add-jessie_backport).
[filesv10.zip](https://github.com/Tecnativa/doodba/files/13902324/filesv10.zip)

Is there a way for use the Doodba v10.0-onbuild image?

Thank you!

**Comment by sergio-teruel** [comment]
Hi @mfloridosygel With this file would be work fine

```
#!/bin/bash
# First remove sources
sed -i '/deb http:\/\/deb.debian.org\/debian jessie main/d' /etc/apt/sources.list
sed -i '/deb http:\/\/security.debian.org\/debian-security jessie\/updates main/d' /etc/apt/sources.list

# Second add archive sources
echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie main" > /etc/apt/sources.list.d/jessie.list
echo "deb [check-valid-until=no] http://archive.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list.d/jessie.list

# PostgreSql repositories
# First one removes the current line
echo "deb https://apt-archive.postgresql.org/pub/repos/apt jessie-pgdg-archive main" > /etc/apt/sources.list.d/postgresql.list
# Second one appends
echo "deb-src https://apt-archive.postgresql.org/pub/repos/apt jessie-pgdg-archive main" >> /etc/apt/sources.list.d/postgresql.list

apt-get -o Acquire::Check-Valid-Until=false update

```

**Comment by mfloridosygel** [comment]
Hi @sergio-teruel ,

Where should I put this file? It overwrites 10-add-jessie_backport?

Finally one more question, should I use the modified files that I attached or should I download again [this commit](https://github.com/Tecnativa/doodba/tree/20dfe8a42487ce00f8220d56e06263c296bfd6db)?

Thanks you

**Comment by sergio-teruel** [comment]
Sorry!!!
Put this file in odoo>custom>build.d folder and you can name a file like 05-update-debian-repos

**Comment by mfloridosygel** [comment]
Hello @sergio-teruel ,

First of all sorry for the delay.

I was testing your solution but It did not work for me, so I used your repositories directly in my Dockerfile and It worked until It reach the line 83:
`RUN gem install --no-rdoc --no-ri --no-update-sources autoprefixer-rails --version '<9.8.6' \
    && gem install --no-rdoc --no-ri --no-update-sources bootstrap-sass --version '<3.4' \
    && rm -Rf ~/.gem /var/lib/gems/*/cache/`

The error is:
`ERROR:  Error installing autoprefixer-rails:
	execjs requires Ruby version >= 2.5.0.`

If I remove these lines It builds correctly. Can I use the image without these lines?

Here you have my Dockerfile
[Dockerfile.zip](https://github.com/Tecnativa/doodba/files/14026738/Dockerfile.zip)

Thank you!
