### ISSUE TITLE
Dockerhub images without onbuild are not generated correctly

### ISSUE THREAD

**Issue by maurochip** [Tecnativa/doodba#605]
I think you had an error generating the last images without onbuild, pulling your images whitout onbuild it's executing the onbuild sentences.
![error1](https://github.com/Tecnativa/doodba/assets/15179177/8f85518c-7fb6-4d96-b78d-619ad422e0d9)
![error2](https://github.com/Tecnativa/doodba/assets/15179177/23abe39f-3ed4-4824-bc4e-471b7f775a9d)

**Comment by pedrobaeza** [comment]
@PCatinean can you say something about this?

**Comment by PCatinean** [comment]
@pedrobaeza @maurochip indeed it's a bug in the build workflow. I will prepare a fix and submit it soon

**Comment by PCatinean** [comment]
@maurochip I have opened a new PR with the fixes and the images from the PR are here: https://hub.docker.com/repository/docker/pledra/doodba/tags?page=1&ordering=last_updated

Could you try pulling from there and let me know if everything is in order?

**Comment by PCatinean** [comment]
@maurochip can you confirm the fix and close this issue?
