### ISSUE TITLE
Can't start instances with `prod.yaml`

### ISSUE THREAD

**Issue by shepilov-vladislav** [Tecnativa/doodba#616]
## Describe the bug

I'm trying to start my production instance using these [instructions](https://github.com/Tecnativa/doodba-copier-template/blob/main/docs/daily-usage.md#booting-production) and I see only these logs

```shell
doodba INFO: Waiting until postgres is listening at db...
doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
doodba INFO: Generating /opt/odoo/auto/odoo.conf file. Overriding any existing...
doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
doodba INFO: Executing /usr/local/bin/odoo
Traceback (most recent call last):
  File "/opt/odoo/common/entrypoint", line 75, in <module>
    os.execvp(extra_command[0], extra_command)
  File "/usr/local/lib/python3.10/os.py", line 575, in execvp
    _execvpe(file, args)
  File "/usr/local/lib/python3.10/os.py", line 598, in _execvpe
    exec_func(file, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

<details>
 <summary>Output command: `docker compose -f prod.yaml run --rm --no-deps odoo ls -lZAR`</summary>
 <pre>
doodba INFO: Waiting until postgres is listening at db...
doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
doodba INFO: Generating /opt/odoo/auto/odoo.conf file. Overriding any existing...
doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
doodba INFO: Executing ls -lZAR
.:
total 24
drwxrwxr-x 1 root odoo ? 4096 Aug  4 09:26 auto
drwxr-xr-x 1 root odoo ? 4096 Aug  4 01:17 common
drwxr-xr-x 1 root odoo ? 4096 Aug  4 09:16 custom
-rw-r----- 1 root odoo ? 5343 Aug  4 01:17 requirements.txt

./auto:
total 12
drwxrwxr-x 1 root odoo ? 4096 Aug  4 09:26 addons
drwxrwxr-x 1 root odoo ? 4096 Aug  4 01:17 geoip
-rw-r--r-- 1 odoo odoo ?  676 Aug  4 09:26 odoo.conf

./auto/addons:
total 0
lrwxrwxrwx 1 odoo odoo ? 32 Aug  4 09:26 rd_base -> ../../custom/src/private/rd_base

./auto/geoip:
total 4
-rw-rw---- 1 root odoo ? 1916 Aug  4 01:17 GeoIP.conf

./common:
total 20
-rwxr-x--- 1 root odoo ? 2707 Aug  4 01:15 build
drwxr-xr-x 1 root odoo ? 4096 Aug  4 01:15 build.d
drwxr-xr-x 1 root odoo ? 4096 Aug  4 01:15 conf.d
-rwxr-x--- 1 root odoo ? 2707 Aug  4 01:15 entrypoint
drwxr-xr-x 1 root odoo ? 4096 Aug  4 01:15 entrypoint.d

./common/build.d:
total 36
-rwxr-x--- 1 root odoo ?  808 Aug  4 01:15 100-repos-aggregate
-rwxr-x--- 1 root odoo ?  987 Aug  4 01:15 200-dependencies
-rwxr-x--- 1 root odoo ?  183 Aug  4 01:15 250-postgres-client
-rwxr-x--- 1 root odoo ?  698 Aug  4 01:15 300-fontconfig
-rwxr-x--- 1 root odoo ? 1715 Aug  4 01:15 400-clean
-rwxr-x--- 1 root odoo ?  191 Aug  4 01:15 500-compile
-rwxr-x--- 1 root odoo ?  540 Aug  4 01:15 700-odoo-install
-rwxr-x--- 1 root odoo ? 1570 Aug  4 01:15 800-permissions
-rwxr-x--- 1 root odoo ?  619 Aug  4 01:15 900-dependencies-cleanup

./common/conf.d:
total 28
-rw-r----- 1 root odoo ? 268 Aug  4 01:15 00-base.conf
-rw-r----- 1 root odoo ? 116 Aug  4 01:15 10-addons.conf
-rw-r----- 1 root odoo ? 216 Aug  4 01:15 20-database.conf
-rw-r----- 1 root odoo ?  77 Aug  4 01:15 30-proxy-mode.conf
-rw-r----- 1 root odoo ? 233 Aug  4 01:15 40-smtp.conf
-rw-r----- 1 root odoo ? 105 Aug  4 01:15 50-demo-data.conf
-rw-r----- 1 root odoo ? 218 Aug  4 01:15 60-geoip.conf

./common/entrypoint.d:
total 20
-rwxr-x--- 1 root odoo ?  239 Aug  4 01:15 20-postgres-wait
-rwxr-x--- 1 root odoo ?  374 Aug  4 01:15 30-unaccent-install
-rwxr-x--- 1 root odoo ?  575 Aug  4 01:15 40-addons-link
-rwxr-x--- 1 root odoo ? 1873 Aug  4 01:15 45-geoip
-rwxr-x--- 1 root odoo ?   99 Aug  4 01:15 50-config-generate

./custom:
total 24
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:32 build.d
drwxr-xr-x 1 root odoo ? 4096 Aug  3 10:44 conf.d
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:32 dependencies
drwxrwxrwx 2 root odoo ? 4096 Aug  3 00:37 entrypoint.d
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:41 src
drwx------ 1 root odoo ? 4096 Aug  2 23:32 ssh

./custom/build.d:
total 0
-rw-r----- 1 root odoo ? 0 Aug  2 23:32 .empty

./custom/conf.d:
total 4
-rw-r----- 1 root odoo ?   0 Aug  2 23:32 .empty
-rw-r----- 1 root odoo ? 675 Aug  3 10:44 100_custom_odoo.conf

./custom/dependencies:
total 4
-rw-r----- 1 root odoo ?   0 Aug  2 23:32 apt.txt
-rw-r----- 1 root odoo ?   0 Aug  2 23:32 apt_build.txt
-rw-r----- 1 root odoo ?   0 Aug  2 23:32 gem.txt
-rw-r----- 1 root odoo ?   0 Aug  2 23:32 npm.txt
-rw-r----- 1 root odoo ? 165 Aug  2 23:32 pip.txt

./custom/entrypoint.d:
total 0

./custom/src:
total 12
-rw-r----- 1 root odoo ?  154 Aug  2 23:32 addons.yaml
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 private
-rw-r----- 1 root odoo ? 2422 Aug  2 23:32 repos.yaml

./custom/src/private:
total 140
-rw-r----- 1 root odoo ?   822 Aug  2 23:40 .copier-answers.yml
-rw-r----- 1 root odoo ?   558 Aug  2 23:40 .editorconfig
-rw-r----- 1 root odoo ?  4418 Aug  2 23:40 .eslintrc.yml
drwxr-xr-x 1 root odoo ?  4096 Aug  3 01:01 .git
drwxr-xr-x 1 root odoo ?  4096 Aug  2 23:40 .github
-rw-r----- 1 root odoo ?   760 Aug  2 23:40 .gitignore
-rw-r----- 1 root odoo ?  3042 Aug  2 23:40 .gitlab-ci.yml
-rw-r----- 1 root odoo ?  4184 Aug  2 23:40 .pre-commit-config.yaml
-rw-r----- 1 root odoo ?   240 Aug  2 23:40 .prettierrc.yml
-rw-r----- 1 root odoo ?  3490 Aug  2 23:40 .pylintrc
-rw-r----- 1 root odoo ?  2627 Aug  2 23:40 .pylintrc-mandatory
-rw-r----- 1 root odoo ?   619 Aug  2 23:40 .ruff.toml
drwxr-xr-x 1 root odoo ?  4096 Aug  2 23:40 .vscode
-rw-r----- 1 root odoo ? 34523 Aug  2 23:40 LICENSE
-rw-r----- 1 root odoo ?  1466 Aug  2 23:40 README.md
-rw-r----- 1 root odoo ? 17026 Aug  2 23:40 poetry.lock
-rw-r----- 1 root odoo ?  1035 Aug  2 23:40 pyproject.toml
drwxr-xr-x 1 root odoo ?  4096 Aug  2 23:40 rd_base

./custom/src/private/.git:
total 56
-rw-r----- 1 root odoo ?  128 Aug  3 00:41 FETCH_HEAD
-rw-r----- 1 root odoo ?   21 Aug  3 00:41 HEAD
-rw-r----- 1 root odoo ?   41 Aug  2 23:41 ORIG_HEAD
drwxr-xr-x 2 root odoo ? 4096 Aug  2 23:40 branches
-rw-r----- 1 root odoo ?  297 Aug  2 23:40 config
-rw-r----- 1 root odoo ?   73 Aug  2 23:40 description
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:41 hooks
-rw-r----- 1 root odoo ? 6240 Aug  3 00:41 index
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 info
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 logs
drwxr-xr-x 1 root odoo ? 4096 Aug  3 00:41 objects
-rw-r----- 1 root odoo ?  112 Aug  2 23:40 packed-refs
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 refs

./custom/src/private/.git/branches:
total 0

./custom/src/private/.git/hooks:
total 64
-rwxr-x--- 1 root odoo ?  478 Aug  2 23:40 applypatch-msg.sample
-rwxr-x--- 1 root odoo ?  896 Aug  2 23:40 commit-msg.sample
-rwxr-x--- 1 root odoo ? 4726 Aug  2 23:40 fsmonitor-watchman.sample
-rwxr-x--- 1 root odoo ?  189 Aug  2 23:40 post-update.sample
-rwxr-x--- 1 root odoo ?  424 Aug  2 23:40 pre-applypatch.sample
-rwxr-x--- 1 root odoo ?  638 Aug  3 00:41 pre-commit
-rwxr-x--- 1 root odoo ? 1643 Aug  2 23:40 pre-commit.sample
-rwxr-x--- 1 root odoo ?  416 Aug  2 23:40 pre-merge-commit.sample
-rwxr-x--- 1 root odoo ? 1374 Aug  2 23:40 pre-push.sample
-rwxr-x--- 1 root odoo ? 4898 Aug  2 23:40 pre-rebase.sample
-rwxr-x--- 1 root odoo ?  544 Aug  2 23:40 pre-receive.sample
-rwxr-x--- 1 root odoo ? 1492 Aug  2 23:40 prepare-commit-msg.sample
-rwxr-x--- 1 root odoo ? 2783 Aug  2 23:40 push-to-checkout.sample
-rwxr-x--- 1 root odoo ? 3650 Aug  2 23:40 update.sample

./custom/src/private/.git/info:
total 4
-rw-r----- 1 root odoo ? 240 Aug  2 23:40 exclude

./custom/src/private/.git/logs:
total 8
-rw-r----- 1 root odoo ? 2541 Aug  3 00:41 HEAD
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 refs

./custom/src/private/.git/logs/refs:
total 8
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 heads
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 remotes

./custom/src/private/.git/logs/refs/heads:
total 4
-rw-r----- 1 root odoo ? 245 Aug  2 23:40 17.0

./custom/src/private/.git/logs/refs/remotes:
total 4
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 origin

./custom/src/private/.git/logs/refs/remotes/origin:
total 4
-rw-r----- 1 root odoo ? 245 Aug  2 23:40 HEAD

./custom/src/private/.git/objects:
total 8
drwxr-xr-x 2 root odoo ? 4096 Aug  2 23:40 info
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 pack

./custom/src/private/.git/objects/info:
total 0

./custom/src/private/.git/objects/pack:
total 56
-rw-r----- 1 root odoo ?  3088 Aug  2 23:40 pack-05eaa2019a130ed726bf0617988f788e10d9b3b1.idx
-rw-r----- 1 root odoo ? 50929 Aug  2 23:40 pack-05eaa2019a130ed726bf0617988f788e10d9b3b1.pack

./custom/src/private/.git/refs:
total 12
drwxr-xr-x 1 root odoo ? 4096 Aug  3 00:41 heads
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 remotes
drwxr-xr-x 2 root odoo ? 4096 Aug  2 23:40 tags

./custom/src/private/.git/refs/heads:
total 4
-rw-r----- 1 root odoo ? 41 Aug  2 23:40 17.0

./custom/src/private/.git/refs/remotes:
total 4
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 origin

./custom/src/private/.git/refs/remotes/origin:
total 4
-rw-r----- 1 root odoo ? 30 Aug  2 23:40 HEAD

./custom/src/private/.git/refs/tags:
total 0

./custom/src/private/.github:
total 4
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 workflows

./custom/src/private/.github/workflows:
total 12
-rw-r----- 1 root odoo ? 1653 Aug  2 23:40 pre-commit.yml
-rw-r----- 1 root odoo ? 2751 Aug  2 23:40 stale.yml
-rw-r----- 1 root odoo ? 2147 Aug  2 23:40 test.yml

./custom/src/private/.vscode:
total 4
-rw-r----- 1 root odoo ? 645 Aug  2 23:40 settings.json

./custom/src/private/rd_base:
total 32
-rw-r----- 1 root odoo ?  107 Aug  2 23:40 README.md
-rw-r----- 1 root odoo ?  740 Aug  2 23:40 __init__.py
-rw-r----- 1 root odoo ? 3330 Aug  2 23:40 __manifest__.py
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 data
-rw-r----- 1 root odoo ?   69 Aug  2 23:40 pyproject.toml
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 security
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 static
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 views

./custom/src/private/rd_base/data:
total 16
-rw-r----- 1 root odoo ?  264 Aug  2 23:40 01_rd_users_data.xml
-rw-r----- 1 root odoo ? 1431 Aug  2 23:40 02_rd_base_report_data.xml
-rw-r----- 1 root odoo ?  321 Aug  2 23:40 03_company_hr_data.xml
-rw-r----- 1 root odoo ?  519 Aug  2 23:40 04_product_category_data.xml

./custom/src/private/rd_base/security:
total 4
-rw-r----- 1 root odoo ? 687 Aug  2 23:40 rd_base_security.xml

./custom/src/private/rd_base/static:
total 4
drwxr-xr-x 1 root odoo ? 4096 Aug  2 23:40 description

./custom/src/private/rd_base/static/description:
total 4
-rw-r----- 1 root odoo ? 2045 Aug  2 23:40 icon.png

./custom/src/private/rd_base/views:
total 4
-rw-r----- 1 root odoo ? 809 Aug  2 23:40 ir_module_views.xml

ls: cannot open directory './custom/ssh': Permission denied
</pre>
</details>

## To Reproduce

**Affected versions**: 17.0

1. Project with Odoo 17.0
2. `docker compose -f prod.yaml up -d`

**Expected behavior** A clear and concise description of what you expected to happen.

Like for other Odoo versions

**Additional context** Add any other context about the problem here. (e.g. OS, Docker
version, ...)

docker --version
`Docker version 27.1.1, build 6312585`

docker compose version

`Docker Compose version v2.29.1`

lsb_release -a

```shell
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Comment by shepilov-vladislav** [comment]
Don't worry, my bad, I forgot to set `AGGREGATE` to `true`.

**Comment by dandenkijin** [comment]
@shepilov-vladislav set AGGREGATE to true where?
