### ISSUE TITLE
Odoo 18 Docker File

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba#625]
Any updates for Odoo 18.0?

**Comment by pedrobaeza** [comment]
Not yet. We are working on it.

**Comment by carlosecv** [comment]
Thank you Pedro

**Comment by juliusm254** [comment]
Can we test?

**Comment by carlosecv** [comment]
I installed odoo 17 version and on repos.yaml you must specify 18.0 version
then you can try odoo 18 on port 17069


Enviado con Gmail Mobile

**Comment by ap-wtioit** [comment]
should be implemented now since https://github.com/Tecnativa/doodba/pull/626 is merged

**Comment by josep-tecnativa** [comment]
FYI, you can also test it using doodba-copier-template since https://github.com/Tecnativa/doodba-copier-template/pull/492 is merged.
