### ISSUE TITLE
add new module to existing repo

### ISSUE THREAD

**Issue by weinni2000** [Tecnativa/doodba#632]
## Describe the bug

I'm new to dooba so maybe it's just a wrong usage.
But if I manually add a new module in one of the repos it's not visible in the frontend.
Even if I rebuild the container with "invoke img-build" it's still not visible. Only if I do a "invoke resetdb" it's accessable. What do I do wrong, or where can be the issue?

## To Reproduce

**Affected versions**:
18

1. Add a new module in one of the repos
2. Try to install the new module

Keep the current state of the db but add the new module.

The addons.yaml looks like this and an invoke git-aggregate also was made before.

mytime:
  - "*"

**Comment by pedrobaeza** [comment]
Please open it in discussions, not as an issue.
