### ISSUE TITLE
[16.0] GeoIP not activating

### ISSUE THREAD

**Issue by JordiBForgeFlow** [Tecnativa/doodba#637]
I have been trying to set up GeoIP in 16.0, without success.

* Added the GEOIP_ACCOUNT_ID and GEOIP_LICENSE_KEY to test.yaml and prod.yaml
* Added geoip_database=/opt/odoo/auto/geoip/GeoLite2-City.mmdb to the config file

Then, when I add to a webpage:
<h1 class="text-center" t-esc="request.geoip"/>

I get: "{}" as answer

Am I missing something? Perhaps a setting in Traefik?

@ap-wtioit Perhaps you know?

**Comment by josep-tecnativa** [comment]
Could you please, give more details of how do you add GEOIP_ACCOUNT_ID and GEOIP_LICENSE_KEY in order to reproduce it?

**Comment by pedrobaeza** [comment]
GeoIP is also applying now rate limits.

**Comment by ap-wtioit** [comment]
unfortunately we are not using traefik (yet?). So the information how to check if it's working is how i usually check:
* Odoo "access" log should show something like:
   ```
   2024-11-12 08:03:47,274 30 INFO prod werkzeug: 62.47.36.129 - - [12/Nov/2024 08:03:47] "GET / HTTP/1.0" 200 - 198 0.066 0.459
   ```
   The ip needs to be the public ip of the user accessing the website (not 192.168.x.x, 10.x.x.x, 172.16.0.0/12, 127.x.x.x)
* Then i check in the backend if the Visitors has the "correct" country flag: 
   ![image](https://github.com/user-attachments/assets/6b992a07-780e-4449-aa53-b7c213304266)

What do you see in those two steps?

**Comment by ap-wtioit** [comment]
@josep-tecnativa you need to register an account with maxmind: https://www.maxmind.com/en/geolite2/signup beware of the rate limit. Testing one instance is usually fine, testing in CI is a challenge (we have additional cache layers for geoip in our images), on prod you should use volumes to share the geoip data folder and most likely add the credentials only to one instance.

**Comment by ap-wtioit** [comment]
@JordiBForgeFlow if you are not testing on a staging instance but in dev, you need to do some trickery to get "public" ips, geoip does not resolve for private ips usually showing up in development.
E.g.:
* define a docker network with a "borrowed" public ip range (unless you are in a company that has IPv4 addresses to spare that you could use in dev) to access your odoo instance, make sure that it is not a network that you interact with on a daily basis (e.g. IPv4 ranges used by mobile network providers that are usually NATed and never host any services are a good pick for this)
* fake the remote address in Odoo's python code before it enters the geoip resolving
* have a ssh reverse tunnel that allows to access your odoo dev via a public well secured nginx

**Comment by JordiBForgeFlow** [comment]
Thanks @ap-wtioit for your help!!

**Comment by ap-wtioit** [comment]
The  [geoip/geolite2](https://github.com/Tecnativa/doodba-copier-template/blob/main/docs/daily-usage.md#geolite2) usage documentation is here (got moved away from the readme in doodba for quite a while). it was initially added in the [PR](https://github.com/Tecnativa/doodba/pull/275) maybe we can improve the readme with a direct link to it. (i had to use google to find were it is at nowadays)
